/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/fanatomy.glb -o src/components/Dashboard/FemaleAnatomyModel.jsx 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

export function Model({ organStress, ...props }) {
  // Use Draco decoder for compressed models
  const { nodes, materials } = useGLTF('/fanatomy-opt.glb', 'https://www.gstatic.com/draco/versioned/decoders/1.5.5/')

  // Mapping of organ keys to their materials in the GLB
  const organMap = {
    heart: [materials.heart_mat],
    lungs: [materials.lung_mat],
    brain: [materials.Brain_mat],
    liver: [materials.Liver_mat],
    kidneys: [materials.kidney_CortexMedulla_mat, materials.kidney_Pyramids_mat],
    pancreas: [materials.gland_mat]
  };

  const getTargetColor = (organ, stress) => {
    let colorHex = 0xffffff;
    switch(organ) {
      case 'lungs':
        if (stress > 60) colorHex = 0x2b2b2b;
        else if (stress > 25) colorHex = 0x696969;
        else colorHex = 0xffb6c1;
        break;
      case 'liver':
        if (stress > 60) colorHex = 0x4a2e15;
        else if (stress > 25) colorHex = 0xc2b280;
        else colorHex = 0x8b3a3a;
        break;
      case 'heart':
        if (stress > 60) colorHex = 0x4a0e17;
        else if (stress > 25) colorHex = 0x8b0000;
        else colorHex = 0xdc143c;
        break;
      case 'brain':
        if (stress > 60) colorHex = 0x808080;
        else if (stress > 25) colorHex = 0xe6e6a1;
        else colorHex = 0xffe4e1;
        break;
      case 'pancreas':
        if (stress > 60) colorHex = 0x654321;
        else if (stress > 25) colorHex = 0xff8c00;
        else colorHex = 0xffb6c1;
        break;
      case 'kidneys':
        if (stress > 60) colorHex = 0x2a1b15;
        else if (stress > 25) colorHex = 0x5c3317;
        else colorHex = 0xa52a2a;
        break;
      default:
        colorHex = 0xffffff;
    }
    return new THREE.Color(colorHex);
  };

  // Animation and realistic color transitions
  useFrame((state, delta) => {
    const stressState = organStress || {};
    Object.entries(organMap).forEach(([key, mats]) => {
      const stress = stressState[key] || 0;
      const targetColor = getTargetColor(key, stress);
      
      mats.forEach(mat => {
        if (!mat) return;
        
        if (!mat.color) mat.color = new THREE.Color(0xffffff);
        
        // Smoothly interpolate base color
        mat.color.lerp(targetColor, delta * 2.0);
        
        // Keep emissive extremely subtle to mimic moisture/highlights, not neon glowing
        mat.emissive.copy(targetColor);
        mat.emissiveIntensity = stress > 25 ? 0.1 : 0; 
      });
    });
  });
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.VH_F_skin.geometry} material={materials.Skin_mat2} />
      <mesh geometry={nodes.VH_F_fat_L.geometry} material={materials.retina_mat3} />
      <mesh geometry={nodes.VH_F_areolar_tubercles_L.geometry} material={materials.Skin_mat} />
      <mesh geometry={nodes.VH_F_nipple_L.geometry} material={materials.Skin_mat} />
      <mesh geometry={nodes.VH_F_areola_L.geometry} material={materials.Skin_mat} />
      <mesh geometry={nodes.VH_F_mammary_lobes_L.geometry} material={materials.BroadLigament_mat} />
      <mesh geometry={nodes.VH_F_main_lactiferous_ducts_L.geometry} material={materials.gland_mat} />
      <mesh geometry={nodes.VH_F_main_lactiferous_sinuses_L.geometry} material={materials.gland_mat} />
      <mesh geometry={nodes.VH_F_suspensory_ligaments_L.geometry} material={materials.Ligament_mat} />
      <mesh geometry={nodes.VH_F_fat_R.geometry} material={materials.retina_mat3} />
      <mesh geometry={nodes.VH_F_areolar_tubercles_R.geometry} material={materials.Skin_mat} />
      <mesh geometry={nodes.VH_F_nipple_R.geometry} material={materials.Skin_mat} />
      <mesh geometry={nodes.VH_F_areola_R.geometry} material={materials.Skin_mat} />
      <mesh geometry={nodes.VH_F_main_lactiferous_sinuses_R.geometry} material={materials.gland_mat} />
      <mesh geometry={nodes.VH_F_main_lactiferous_ducts_R.geometry} material={materials.gland_mat} />
      <mesh geometry={nodes.VH_F_mammary_lobes_R.geometry} material={materials.BroadLigament_mat} />
      <mesh geometry={nodes.VH_F_suspensory_ligaments_R.geometry} material={materials.Ligament_mat} />
      <mesh geometry={nodes.VH_F_retina_R.geometry} material={materials['eye_edits_012022:retina1']}>
        <mesh geometry={nodes.VH_F_fovea_R.geometry} material={materials['eye_edits_012024:fovea_mat']} />
        <mesh geometry={nodes.VH_F_macula_lutea_R.geometry} material={materials['eye_edits_012024:macula']} />
        <mesh geometry={nodes.VH_F_optic_disc_R.geometry} material={materials['eye_edits_012022:pasted__retina3']} />
      </mesh>
      <mesh geometry={nodes.VH_F_sclera_R.geometry} material={materials['eye_edits_012022:Eyeball_Mat']} />
      <mesh geometry={nodes.VH_F_optic_choroid_R.geometry} material={materials['eye_edits_012024:choroid_mat']} />
      <mesh geometry={nodes.VH_F_pupil_R.geometry} material={materials['eye_edits_012022:pupil1']} />
      <mesh geometry={nodes.VH_F_ciliary_processes_R.geometry} material={materials['eye_edits_012024:brain_mat1']} />
      <mesh geometry={nodes.VH_F_suspensory_ligament_of_lens_R.geometry} material={materials['eye_edits_012024:iris_mat']} />
      <mesh geometry={nodes.VH_F_ora_serrata_of_retina_R.geometry} material={materials['eye_edits_012024:Ora_serrata_Mat']} />
      <mesh geometry={nodes.VH_F_corneo_scleral_junction_R.geometry} material={materials['eye_edits_012024:limbus1']} />
      <mesh geometry={nodes.VH_F_lens_R.geometry} material={materials['eye_edits_012022:lens1']} />
      <mesh geometry={nodes.VH_F_schlemms_canal_R.geometry} material={materials['eye_edits_012024:Skin_Mat']} />
      <mesh geometry={nodes.VH_F_aqueous_humor_R.geometry} material={materials['eye_edits_012022:humor_mat']} />
      <mesh geometry={nodes.VH_F_ciliary_body_R.geometry} material={materials['eye_edits_012035:lung_mat']}>
        <mesh geometry={nodes.VH_F_ciliary_muscle_R.geometry} material={materials['eye_edits_012036:lung_mat']} />
      </mesh>
      <mesh geometry={nodes.VH_F_trabecular_meshwork_R.geometry} material={materials['eye_edits_012024:meniscus_mat']} />
      <mesh geometry={nodes.VH_F_iris_R.geometry} material={materials['eye_edits_012022:iris_mat']} />
      <mesh geometry={nodes.VH_F_bulbar_conjunctiva_R.geometry} material={materials['eye_edits_012022:Bone_Mat']} />
      <mesh geometry={nodes.VH_F_cornea_R.geometry} material={materials['eye_edits_012022:Cornea_mat']} />
      <mesh geometry={nodes.VH_F_vitreous_humor_R.geometry} material={materials['eye_edits_012022:humor_mat']} />
      <mesh geometry={nodes.VH_F_palpebral_conjunctiva_of_right_upper_eyelid.geometry} material={materials.pasted__pasted__pasted__conjunctiva_Mat1} />
      <mesh geometry={nodes.VH_F_palpebral_conjunctiva_of_right_lower_eyelid.geometry} material={materials.pasted__pasted__pasted__conjunctiva_Mat1} />
      <mesh geometry={nodes.VH_F_retina_L.geometry} material={materials.retina_mat}>
        <mesh geometry={nodes.VH_F_fovea_L.geometry} material={materials.fovea_mat} />
        <mesh geometry={nodes.VH_F_macula_lutea_L.geometry} material={materials.macula_mat} />
        <mesh geometry={nodes.VH_F_optic_disc_L.geometry} material={materials.retina_mat} />
      </mesh>
      <mesh geometry={nodes.VH_F_vitreous_humor_L.geometry} material={materials['eye_edits_012022:humor_mat']} />
      <mesh geometry={nodes.VH_F_cornea_L.geometry} material={materials['eye_edits_012024:Cornea_mat']} />
      <mesh geometry={nodes.VH_F_bulbar_conjunctiva_L.geometry} material={materials['eye_edits_012024:Bone_Mat']} />
      <mesh geometry={nodes.VH_F_iris_L.geometry} material={materials.iris_mat} />
      <mesh geometry={nodes.VH_F_trabecular_meshwork_L.geometry} material={materials['eye_edits_012022:meniscus_mat']} />
      <mesh geometry={nodes.VH_F_ciliary_body_L.geometry} material={materials['eye_edits_012022:lung_mat']}>
        <mesh geometry={nodes.VH_F_ciliary_muscle_L.geometry} material={materials['eye_edits_012022:lung_mat']} />
      </mesh>
      <mesh geometry={nodes.VH_F_aqueous_humor_L.geometry} material={materials.humours_mat} />
      <mesh geometry={nodes.VH_F_schlemms_canal_L.geometry} material={materials['eye_edits_012022:Skin_Mat']} />
      <mesh geometry={nodes.VH_F_lens_L.geometry} material={materials['eye_edits_012022:lens1']} />
      <mesh geometry={nodes.VH_F_corneo_scleral_junction_L.geometry} material={materials['eye_edits_012022:limbus1']} />
      <mesh geometry={nodes.VH_F_ora_serrata_of_retina_L.geometry} material={materials['eye_edits_012022:Ora_serrata_Mat']} />
      <mesh geometry={nodes.VH_F_suspensory_ligament_of_lens_L.geometry} material={materials['eye_edits_012022:iris_mat']} />
      <mesh geometry={nodes.VH_F_ciliary_processes_L.geometry} material={materials['eye_edits_012022:brain_mat1']} />
      <mesh geometry={nodes.VH_F_pupil_L.geometry} material={materials.pupil_mat} />
      <mesh geometry={nodes.VH_F_optic_choroid_L.geometry} material={materials.choroid_mat} />
      <mesh geometry={nodes.VH_F_sclera_L.geometry} material={materials['eye_edits_012043:Eyeball_Mat']} />
      <mesh geometry={nodes.VH_F_palpebral_conjunctiva_of_left_upper_eyelid.geometry} material={materials.pasted__pasted__pasted__conjunctiva_Mat1} />
      <mesh geometry={nodes.VH_F_palpebral_conjunctiva_of_left_lower_eyelid.geometry} material={materials.pasted__pasted__pasted__conjunctiva_Mat1} />
      <mesh geometry={nodes.VH_F_dura_mater_right.geometry} material={materials.pasted__pasted__dura_mater_mat} />
      <mesh geometry={nodes.VH_F_right_optic_nerve.geometry} material={materials['eye_edits_012022:pasted__retina3']} />
      <mesh geometry={nodes.VH_F_dura_mater_left.geometry} material={materials.pasted__pasted__pasted__dura_mater_mat} />
      <mesh geometry={nodes.VH_F_left_optic_nerve.geometry} material={materials['eye_edits_012024:pasted__retina3']} />
      <mesh geometry={nodes.VH_F_optic_chiasm.geometry} material={materials.retina_mat} />
      <mesh geometry={nodes.Allen_olfactory_bulb_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_anterior_olfactory_nucleus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_piriform_region_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_frontal_agranular_insular_cortex_area_Fl_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_temporal_agranular_insular_cortex_area_Tl_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_head_of_caudate_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_body_of_caudate_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_tail_of_caudate_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_putamen_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_nucleus_accumbens_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_external_segment_of_globus_pallidus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_internal_segment_of_globus_pallidus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_claustrum_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_basal_forebrain_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_septal_nuclei_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_amygdaloid_complex_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_anterior_amygdaloid_area_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_central_nuclear_group_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_lateral_nucleus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_basolateral_nucleus_basal_nucleus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_basomedial_nucleus_accessory_basal_nucleus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_anterior_cortical_nucleus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_posterior_cortical_nucleus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_medial_nucleus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_amygdalohippocampal_area_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_bed_nucleus_of_stria_terminalis_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_thalamus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_anterior_nuclear_complex_of_thalamus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_lateral_dorsal_nucleus_of_thalamus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_mediodorsal_nucleus_of_thalamus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_reuniens_nucleus_medioventral_nucleus_of_thalamus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_lateral_posterior_nucleus_of_thalamus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_pulvinar_of_thalamus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_ventral_anterior_nucleus_of_thalamus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_ventral_lateral_nucleus_of_thalamus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_ventral_posterior_lateral_nucleus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_ventral_posterior_medial_nucleus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_dorsal_lateral_geniculate_nucleus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_medial_geniculate_nuclei_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_centromedian_nucleus_of_thalamus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_parafascicular_nucleus_of_thalamus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_habenular_nuclei_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_pineal_body_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_zona_incerta_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_supraoptic_region_of_HTH_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_preoptic_region_of_HTH_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_tuberal_region_of_HTH_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_white_matter_of_forebrain_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_anterior_commissure_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_corpus_callosum_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_fornix_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_mammillothalamic_tract_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_optic_tract_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_anterior_horn_of_lateral_ventricle_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_body_of_lateral_ventricle_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_posterior_horn_of_lateral_ventricle_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_inferior_horn_of_lateral_ventricle_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_third_ventricle_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_cerebellar_vermis_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_cerebellar_deep_nuclei_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_white_matter_of_hindbrain_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_olfactory_tract_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_precentral_gyrus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_superior_frontal_gyrus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_middle_frontal_gyrus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_inferior_frontal_gyrus_triangular_part_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_inferior_frontal_gyrus_opercular_part_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_gyrus_rectus_straight_gyrus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_medial_orbital_gyrus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_anterior_intermediate_orbital_gyrus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_posterior_intermediate_orbital_gyrus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_lateral_orbital_gyrus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_paracentral_lobule_rostral_part_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_frontal_operculum_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_postcentral_gyrus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_supraparietal_lobule_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_supramarginal_gyrus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_angular_gyrus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_precuneus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_paracentral_lobule_caudal_part_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_superior_temporal_gyrus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_middle_temporal_gyrus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_inferior_temporal_gyrus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_occipitotemporal_fusiform_gyrus_temporal_part_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_transverse_temporal_gyrus_Heschls_gyrus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_planum_temporale_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_temporal_pole_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_planum_polare_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_occipital_pole_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_cuneus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_lingual_gyrus_medial_occipitotemporal_gyrus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_lateral_occipitotemporal_fusiform_gyrus_occipital_part_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_inferior_occipital_gyrus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_superior_occipital_gyrus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_cingulate_gyrus_rostral_anterior_part_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_cingulate_gyrus_caudal_posterior_part_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_ingulo_parahippocampal_isthmus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_subcallosal_gyrus_parolfactory_gyrus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_anterior_parahippocampal_gyrus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_posterior_parahippocampal_gyrus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_gyrus_ambiens_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_head_of_hippocampus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_body_of_hippocampus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_tail_of_hippocampus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_long_insular_gyri_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_short_insular_gyri_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_limen_insula_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_pretectal_region_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_substantia_nigra_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_superior_colliculus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_cerebral_peduncle_crus_cerebri_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_superior_cerebellar_peduncle_brachium_conjunctivum_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_cerebral_aqueduct_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_paravermis_of_cerebellum_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_lateral_hemisphere_of_cerebellum_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_basilar_part_of_pons_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_pontine_tegmentum_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_pyramidal_part_of_medulla_oblongata_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_tegmentum_of_medulla_oblongata_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_inferior_olive_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_middle_cerebellar_peduncle_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_fourth_ventricle_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_central_canal_of_medulla_oblongata_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_midline_nuclear_complex_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_lateral_olfactory_gyrus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_parietal_operculum_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_optic_radiation_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_posteroventral_putamen_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_atrium_of_lateral_ventricle_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_paracingulate_gyrus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_rostral_gyrus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_frontomarginal_gyrus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_frontal_pole_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_inferior_cerebellar_peduncle_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_perirhinal_gyrus_rostral_part_of_FuGt_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_olfactory_bulb_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_anterior_olfactory_nucleus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_piriform_region_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_frontal_agranular_insular_cortex_area_Fl_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_temporal_agranular_insular_cortex_area_Tl_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_head_of_caudate_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_body_of_caudate_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_tail_of_caudate_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_putamen_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_nucleus_accumbens_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_external_segment_of_globus_pallidus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_internal_segment_of_globus_pallidus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_claustrum_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_basal_forebrain_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_septal_nuclei_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_amygdaloid_complex_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_anterior_amygdaloid_area_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_central_nuclear_group_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_lateral_nucleus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_basolateral_nucleus_basal_nucleus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_basomedial_nucleus_accessory_basal_nucleus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_anterior_cortical_nucleus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_posterior_cortical_nucleus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_medial_nucleus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_amygdalohippocampal_area_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_bed_nucleus_of_stria_terminalis_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_thalamus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_anterior_nuclear_complex_of_thalamus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_lateral_dorsal_nucleus_of_thalamus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_mediodorsal_nucleus_of_thalamus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_reuniens_nucleus_medioventral_nucleus_of_thalamus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_lateral_posterior_nucleus_of_thalamus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_pulvinar_of_thalamus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_ventral_anterior_nucleus_of_thalamus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_ventral_lateral_nucleus_of_thalamus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_ventral_posterior_lateral_nucleus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_ventral_posterior_medial_nucleus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_dorsal_lateral_geniculate_nucleus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_medial_geniculate_nuclei_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_centromedian_nucleus_of_thalamus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_parafascicular_nucleus_of_thalamus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_habenular_nuclei_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_pineal_body_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_zona_incerta_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_supraoptic_region_of_HTH_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_white_matter_of_forebrain_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_anterior_commissure_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_corpus_callosum_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_fornix_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_mammillothalamic_tract_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_optic_tract_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_anterior_horn_of_lateral_ventricle_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_body_of_lateral_ventricle_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_posterior_horn_of_lateral_ventricle_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_inferior_horn_of_lateral_ventricle_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_third_ventricle_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_cerebellar_vermis_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_cerebellar_deep_nuclei_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_white_matter_of_hindbrain_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_olfactory_tract_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_precentral_gyrus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_superior_frontal_gyrus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_middle_frontal_gyrus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_inferior_frontal_gyrus_triangular_part_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_inferior_frontal_gyrus_opercular_part_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_gyrus_rectus_straight_gyrus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_medial_orbital_gyrus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_anterior_intermediate_orbital_gyrus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_posterior_intermediate_orbital_gyrus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_lateral_orbital_gyrus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_paracentral_lobule_rostral_part_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_frontal_operculum_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_postcentral_gyrus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_supraparietal_lobule_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_supramarginal_gyrus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_angular_gyrus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_precuneus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_paracentral_lobule_caudal_part_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_superior_temporal_gyrus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_middle_temporal_gyrus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_inferior_temporal_gyrus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_occipitotemporal_fusiform_gyrus_temporal_part_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_transverse_temporal_gyrus_Heschls_gyrus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_planum_temporale_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_temporal_pole_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_planum_polare_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_occipital_pole_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_cuneus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_lingual_gyrus_medial_occipitotemporal_gyrus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_lateral_occipitotemporal_fusiform_gyrus_occipital_part_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_inferior_occipital_gyrus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_superior_occipital_gyrus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_cingulate_gyrus_rostral_anterior_part_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_cingulate_gyrus_caudal_posterior_part_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_ingulo_parahippocampal_isthmus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_subcallosal_gyrus_parolfactory_gyrus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_anterior_parahippocampal_gyrus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_posterior_parahippocampal_gyrus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_gyrus_ambiens_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_head_of_hippocampus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_body_of_hippocampus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_tail_of_hippocampus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_long_insular_gyri_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_short_insular_gyri_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_limen_insula_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_pretectal_region_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_red_nucleus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_substantia_nigra_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_superior_colliculus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_inferior_colliculus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_cerebral_peduncle_crus_cerebri_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_superior_cerebellar_peduncle_brachium_conjunctivum_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_cerebral_aqueduct_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_paravermis_of_cerebellum_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_lateral_hemisphere_of_cerebellum_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_basilar_part_of_pons_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_pontine_tegmentum_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_pyramidal_part_of_medulla_oblongata_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_tegmentum_of_medulla_oblongata_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_inferior_olive_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_inferior_cerebellar_peduncle_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_middle_cerebellar_peduncle_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_fourth_ventricle_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_central_canal_of_medulla_oblongata_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_midline_nuclear_complex_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_lateral_olfactory_gyrus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_parietal_operculum_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_optic_radiation_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_posteroventral_putamen_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_atrium_of_lateral_ventricle_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_paracingulate_gyrus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_rostral_gyrus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_frontomarginal_gyrus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_frontal_pole_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_perirhinal_gyrus_rostral_part_of_FuGt_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_hypothalamus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_hypothalamus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_subthalamic_nucleus_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_mammillary_region_of_HTH_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_midbrain_tegmentum_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_tuberal_region_of_HTH_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_preoptic_region_of_HTH_R.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_midbrain_tegmentum_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_red_nucleus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_inferior_colliculus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_mammillary_region_of_HTH_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.Allen_subthalamic_nucleus_L.geometry} material={materials.Brain_mat} />
      <mesh geometry={nodes.VH_F_C1_segment_of_cervical_spinal_cord.geometry} material={materials.pasted__retina_mat6} />
      <mesh geometry={nodes.VH_F_C2_segment_of_cervical_spinal_cord.geometry} material={materials.pasted__retina_mat6} />
      <mesh geometry={nodes.VH_F_C3_segment_of_cervical_spinal_cord.geometry} material={materials.pasted__retina_mat6} />
      <mesh geometry={nodes.VH_F_C4_segment_of_cervical_spinal_cord.geometry} material={materials.pasted__retina_mat6} />
      <mesh geometry={nodes.VH_F_C5_segment_of_cervical_spinal_cord.geometry} material={materials.pasted__retina_mat6} />
      <mesh geometry={nodes.VH_F_C6_segment_of_cervical_spinal_cord.geometry} material={materials.pasted__retina_mat6} />
      <mesh geometry={nodes.VH_F_C7_segment_of_cervical_spinal_cord.geometry} material={materials.pasted__retina_mat6} />
      <mesh geometry={nodes.VH_F_C8_segment_of_cervical_spinal_cord.geometry} material={materials.pasted__retina_mat6} />
      <mesh geometry={nodes.VH_F_first_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina_mat6} />
      <mesh geometry={nodes.VH_F_second_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina_mat6} />
      <mesh geometry={nodes.VH_F_third_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina_mat6} />
      <mesh geometry={nodes.VH_F_fourth_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina_mat6} />
      <mesh geometry={nodes.VH_F_fifth_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina_mat6} />
      <mesh geometry={nodes.VH_F_seventh_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina_mat6} />
      <mesh geometry={nodes.VH_F_eigth_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina_mat6} />
      <mesh geometry={nodes.VH_F_sixth_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina_mat6} />
      <mesh geometry={nodes.VH_F_ninth_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina_mat6} />
      <mesh geometry={nodes.VH_F_tenth_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina_mat6} />
      <mesh geometry={nodes.VH_F_eleventh_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina_mat6} />
      <mesh geometry={nodes.VH_F_twelfth_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina_mat6} />
      <mesh geometry={nodes.VH_F_first_lumbar_spinal_cord_segment.geometry} material={materials.pasted__retina_mat6} />
      <mesh geometry={nodes.VH_F_second_lumbar_spinal_cord_segment.geometry} material={materials.pasted__retina_mat6} />
      <mesh geometry={nodes.VH_F_third_lumbar_spinal_cord_segment.geometry} material={materials.pasted__retina_mat6} />
      <mesh geometry={nodes.VH_F_fourth_lumbar_spinal_cord_segment.geometry} material={materials.pasted__retina_mat6} />
      <mesh geometry={nodes.VH_F_fifth_lumbar_spinal_cord_segment.geometry} material={materials.pasted__retina_mat6} />
      <mesh geometry={nodes.VH_F_first_sacral_spinal_cord_segment.geometry} material={materials.pasted__retina_mat6} />
      <mesh geometry={nodes.VH_F_second_sacral_spinal_cord_segment.geometry} material={materials.pasted__retina_mat6} />
      <mesh geometry={nodes.VH_F_third_sacral_spinal_cord_segment.geometry} material={materials.pasted__retina_mat6} />
      <mesh geometry={nodes.VH_F_fourth_sacral_spinal_cord_segment.geometry} material={materials.pasted__retina_mat6} />
      <mesh geometry={nodes.VH_F_medial_rectus_extraocular_muscle_L.geometry} material={materials['eye_edits_012024:muscle_mat']} />
      <mesh geometry={nodes.VH_F_inferior_rectus_extraocular_muscle_L.geometry} material={materials['eye_edits_012024:muscle_mat']} />
      <mesh geometry={nodes.VH_F_superior_rectus_extraocular_muscle_L.geometry} material={materials['eye_edits_012024:muscle_mat']} />
      <mesh geometry={nodes.VH_F_inferior_oblique_extraocular_muscle_L.geometry} material={materials['eye_edits_012024:muscle_mat']} />
      <mesh geometry={nodes.VH_F_lateral_rectus_extraocular_muscle_L.geometry} material={materials['eye_edits_012024:muscle_mat']} />
      <mesh geometry={nodes.VH_F_superior_oblique_extraocular_muscle_L.geometry} material={materials['eye_edits_012024:muscle_mat']} />
      <mesh geometry={nodes.VH_F_medial_rectus_extraocular_muscle_R.geometry} material={materials['eye_edits_012022:muscle_mat']} />
      <mesh geometry={nodes.VH_F_inferior_rectus_extraocular_muscle_R.geometry} material={materials['eye_edits_012022:muscle_mat']} />
      <mesh geometry={nodes.VH_F_superior_rectus_extraocular_muscle_R.geometry} material={materials['eye_edits_012022:muscle_mat']} />
      <mesh geometry={nodes.VH_F_inferior_oblique_extraocular_muscle_R.geometry} material={materials['eye_edits_012022:muscle_mat']} />
      <mesh geometry={nodes.VH_F_lateral_rectus_extraocular_muscle_R.geometry} material={materials['eye_edits_012022:muscle_mat']} />
      <mesh geometry={nodes.VH_F_superior_oblique_extraocular_muscle_R.geometry} material={materials['eye_edits_012022:muscle_mat']} />
      <mesh geometry={nodes.VH_F_rectus_femoris_L.geometry} material={materials.Muscle_mat6}>
        <mesh geometry={nodes.VH_F_tendon_of_quadriceps_femoris_L.geometry} material={materials.ureter_mat8} />
      </mesh>
      <mesh geometry={nodes.VH_F_rectus_femoris_R.geometry} material={materials.Muscle_mat5}>
        <mesh geometry={nodes.VH_F_tendon_of_quadriceps_femoris_R.geometry} material={materials.ureter_mat7} />
      </mesh>
      <mesh geometry={nodes.VH_F_vagina.geometry} material={materials.BroadLigament_mat}>
        <mesh geometry={nodes.VH_F_cervicovaginal_junction.geometry} material={materials.BroadLigament_mat} />
      </mesh>
      <mesh geometry={nodes.VH_F_basal_plate.geometry} material={materials.pasted__Uterus_Mat} />
      <mesh geometry={nodes.VH_F_chorionic_plate.geometry} material={materials.pasted__Uterus_Mat} />
      <mesh geometry={nodes.VH_F_placenta_vessels.geometry} material={materials.pasted__Arteries_Mat} />
      <mesh geometry={nodes.VH_F_amnion.geometry} material={materials.pasted__mucosa_mat} />
      <mesh geometry={nodes.VH_F_umbilical_cord.geometry} material={materials.pasted__mucosa_mat} />
      <mesh geometry={nodes.VH_F_umbilical_artery_1.geometry} material={materials.pasted__Arteries_Mat} />
      <mesh geometry={nodes.VH_F_umbilical_artery_2.geometry} material={materials.pasted__Arteries_Mat} />
      <mesh geometry={nodes.VH_F_umbilical_vein.geometry} material={materials.pasted__Vein_mat} />
      <mesh geometry={nodes.VH_F_ampulla_of_uterine_tube_R.geometry} material={materials.Uterus_Mat} />
      <mesh geometry={nodes.VH_F_isthmus_of_fallopian_tube_R.geometry} material={materials.Uterus_Mat} />
      <mesh geometry={nodes.VH_F_fibria_of_uterine_tube_R.geometry} material={materials.Uterus_Mat} />
      <mesh geometry={nodes.VH_F_uterine_tube_infundibulum_R.geometry} material={materials.Uterus_Mat} />
      <mesh geometry={nodes.VH_F_uterine_tube_infundibulum_L.geometry} material={materials.Uterus_Mat} />
      <mesh geometry={nodes.VH_F_fibria_of_uterine_tube_L.geometry} material={materials.Uterus_Mat} />
      <mesh geometry={nodes.VH_F_isthmus_of_fallopian_tube_L.geometry} material={materials.Uterus_Mat} />
      <mesh geometry={nodes.VH_F_ampulla_of_uterine_tube_L.geometry} material={materials.Uterus_Mat} />
      <mesh geometry={nodes.VH_F_uterovesical_pouch.geometry} material={materials.BroadLigament_mat} />
      <mesh geometry={nodes.VH_F_broad_ligament.geometry} material={materials.BroadLigament_mat}>
        <mesh geometry={nodes.VH_F_mesosalpinx_L.geometry} material={materials.BroadLigament_mat} />
        <mesh geometry={nodes.VH_F_mesosalpinx_R.geometry} material={materials.BroadLigament_mat} />
        <mesh geometry={nodes.VH_F_mesovarium_R.geometry} material={materials.BroadLigament_mat} />
        <mesh geometry={nodes.VH_F_mesovarium_L.geometry} material={materials.BroadLigament_mat} />
      </mesh>
      <mesh geometry={nodes.VH_F_right_round_ligament_of_uterus.geometry} material={materials.Ligament_mat} />
      <mesh geometry={nodes.VH_F_left_round_ligament_of_uterus.geometry} material={materials.Ligament_mat} />
      <mesh geometry={nodes.VH_F_right_uterosacral_ligament.geometry} material={materials.Ligament_mat} />
      <mesh geometry={nodes.VH_F_left_uterosacral_ligament.geometry} material={materials.Ligament_mat} />
      <mesh geometry={nodes.VH_F_right_cardinal_ligament_of_uterus.geometry} material={materials.Ligament_mat} />
      <mesh geometry={nodes.VH_F_left_cardinal_ligament_of_uterus.geometry} material={materials.Ligament_mat} />
      <mesh geometry={nodes.VH_F_suspensory_ligament_of_ovary_R.geometry} material={materials.Ligament_mat} />
      <mesh geometry={nodes.VH_F_suspensory_ligament_of_ovary_L.geometry} material={materials.Ligament_mat} />
      <mesh geometry={nodes.VH_F_ovarian_ligament_L.geometry} material={materials.Ligament_mat} />
      <mesh geometry={nodes.VH_F_ovarian_ligament_R.geometry} material={materials.Ligament_mat} />
      <mesh geometry={nodes.VH_F_left_ovary.geometry} material={materials.Ovary_mat} />
      <mesh geometry={nodes.VH_F_right_ovary.geometry} material={materials.Ovary_mat} />
      <mesh geometry={nodes.VH_F_abdominal_ostium_of_uterine_tube.geometry} material={materials.Uterus_Mat} />
      <mesh geometry={nodes.VH_F_body_of_uterus.geometry} material={materials.Uterus_Mat} />
      <mesh geometry={nodes.VH_F_fundus_of_uterus.geometry} material={materials.Uterus_Mat} />
      <mesh geometry={nodes.VH_F_cornua.geometry} material={materials.Uterus_Mat} />
      <mesh geometry={nodes.VH_F_lower_uterine_segment.geometry} material={materials.Uterus_Mat} />
      <mesh geometry={nodes.VH_F_posterior_wall_of_uterus.geometry} material={materials.Uterus_Mat} />
      <mesh geometry={nodes.VH_F_anterior_wall_of_uterus.geometry} material={materials.Uterus_Mat} />
      <mesh geometry={nodes.VH_F_cervix.geometry} material={materials.Uterus_Mat}>
        <mesh geometry={nodes.VH_F_internal_cervical_os.geometry} material={materials.Uterus_Mat} />
        <mesh geometry={nodes.VH_F_external_cervical_os.geometry} material={materials.Uterus_Mat} />
      </mesh>
      <mesh geometry={nodes.VH_F_palatine_tonsil_L.geometry} material={materials['eye_edits_012036:lung_mat']} />
      <mesh geometry={nodes.VH_F_palatine_tonsil_R.geometry} material={materials['eye_edits_012036:lung_mat']} />
      <mesh geometry={nodes.VH_F_hepatic_flexure_of_colon.geometry} material={materials.colon_mat1} />
      <mesh geometry={nodes.VH_F_transverse_colon.geometry} material={materials.colon_mat1} />
      <mesh geometry={nodes.VH_F_ascending_colon.geometry} material={materials.colon_mat1} />
      <mesh geometry={nodes.VH_F_vermiform_appendix.geometry} material={materials.colon_mat1} />
      <mesh geometry={nodes.VH_F_descending_colon.geometry} material={materials.colon_mat1} />
      <mesh geometry={nodes.VH_F_ileocecal_valve.geometry} material={materials.colon_mat1} />
      <mesh geometry={nodes.VH_F_caecum.geometry} material={materials.colon_mat1} />
      <mesh geometry={nodes.VH_F_rectum.geometry} material={materials.colon_mat1} />
      <mesh geometry={nodes.VH_F_sigmoid_colon.geometry} material={materials.colon_mat1} />
      <mesh geometry={nodes.VH_F_splenic_flexure_of_colon.geometry} material={materials.colon_mat1} />
      <mesh geometry={nodes.VH_F_jejenum.geometry} material={materials.sm_intestine_mat} />
      <mesh geometry={nodes.VH_F_ileum.geometry} material={materials.sm_intestine_mat}>
        <mesh geometry={nodes.VH_F_ileum_terminal.geometry} material={materials.sm_intestine_mat} />
      </mesh>
      <mesh geometry={nodes.VH_F_duodenum_superior.geometry} material={materials.sm_intestine_mat}>
        <mesh geometry={nodes.VH_F_duodenal_ampulla.geometry} material={materials.sm_intestine_mat} />
      </mesh>
      <mesh geometry={nodes.VH_F_duodenum_descending.geometry} material={materials.sm_intestine_mat} />
      <mesh geometry={nodes.VH_F_sphincter_of_heptopancreatic_ampulla.geometry} material={materials.sm_intestine_mat} />
      <mesh geometry={nodes.VH_F_duodenum_ascending.geometry} material={materials.sm_intestine_mat} />
      <mesh geometry={nodes.VH_F_duodenum_horizontal.geometry} material={materials.sm_intestine_mat} />
      <mesh geometry={nodes.VH_F_right_hepatic_duct.geometry} material={materials.Gall_mat} />
      <mesh geometry={nodes.VH_F_left_hepatic_duct.geometry} material={materials.Gall_mat} />
      <mesh geometry={nodes.VH_F_common_hepatic_duct.geometry} material={materials.Gall_mat} />
      <mesh geometry={nodes.VH_F_hepatopancreatic_ampulla.geometry} material={materials.Gall_mat} />
      <mesh geometry={nodes.VH_F_dorsal_pancreatic_duct.geometry} material={materials.Gall_mat} />
      <mesh geometry={nodes.VH_F_common_bile_duct.geometry} material={materials.Gall_mat} />
      <mesh geometry={nodes.VH_F_ventral_pancreatic_duct.geometry} material={materials.Gall_mat} />
      <mesh geometry={nodes.VH_F_cystic_duct.geometry} material={materials.Gall_mat} />
      <mesh geometry={nodes.VH_F_gastric_impression_of_liver.geometry} material={materials.Liver_mat} />
      <mesh geometry={nodes.VH_F_suprarenal_impression_of_liver.geometry} material={materials.Liver_mat} />
      <mesh geometry={nodes.VH_F_renal_impression_of_liver.geometry} material={materials.Liver_mat} />
      <mesh geometry={nodes.VH_F_duodenal_impression_of_liver.geometry} material={materials.Liver_mat} />
      <mesh geometry={nodes.VH_F_esophageal_impression_of_liver.geometry} material={materials.Liver_mat} />
      <mesh geometry={nodes.VH_F_porta_hepatis.geometry} material={materials.Liver_mat} />
      <mesh geometry={nodes.VH_F_colic_impression_of_liver.geometry} material={materials.Liver_mat} />
      <mesh geometry={nodes.VH_F_capsule_of_the_liver.geometry} material={materials.Liver_mat} />
      <mesh geometry={nodes.VH_F_bare_area_of_liver.geometry} material={materials.Liver_mat} />
      <mesh geometry={nodes.VH_F_diaphragmatic_surface_of_liver.geometry} material={materials.Liver_mat} />
      <mesh geometry={nodes.VH_F_left_anterolateral_segment.geometry} material={materials.Liver_mat} />
      <mesh geometry={nodes.VH_F_left_superomedial_segment.geometry} material={materials.Liver_mat} />
      <mesh geometry={nodes.VH_F_left_superomedial_segment1.geometry} material={materials.Liver_mat} />
      <mesh geometry={nodes.VH_F_left_inferomedial_segment.geometry} material={materials.Liver_mat}>
        <mesh geometry={nodes.VH_F_quadrate_lobe.geometry} material={materials.Liver_mat} />
      </mesh>
      <mesh geometry={nodes.VH_F_right_anterosuperior_segment.geometry} material={materials.Liver_mat} />
      <mesh geometry={nodes.VH_F_right_posteroinferior_segment.geometry} material={materials.Liver_mat} />
      <mesh geometry={nodes.VH_F_right_posterosuperior_segment.geometry} material={materials.Liver_mat} />
      <mesh geometry={nodes.VH_F_right_anteroinferior_segment.geometry} material={materials.Liver_mat} />
      <mesh geometry={nodes.VH_F_caudate_lobe.geometry} material={materials.Liver_mat} />
      <mesh geometry={nodes.VH_F_coronary_ligament_of_liver.geometry} material={materials.Ligament_mat} />
      <mesh geometry={nodes.VH_F_falciform_ligament.geometry} material={materials.Ligament_mat} />
      <mesh geometry={nodes.VH_F_triangular_ligament_of_liver.geometry} material={materials.Ligament_mat} />
      <mesh geometry={nodes.VH_F_ligamentum_venosum.geometry} material={materials.Ligament_mat} />
      <mesh geometry={nodes.VH_F_round_ligament_of_liver.geometry} material={materials.Ligament_mat} />
      <mesh geometry={nodes.VH_F_hepataduodenal_ligament.geometry} material={materials.Ligament_mat} />
      <mesh geometry={nodes.VH_F_tail_of_pancreas.geometry} material={materials.gland_mat} />
      <mesh geometry={nodes.VH_F_body_of_pancreas.geometry} material={materials.gland_mat} />
      <mesh geometry={nodes.VH_F_ucinate_process1.geometry} material={materials.gland_mat} />
      <mesh geometry={nodes.VH_F_head_of_pancreas.geometry} material={materials.gland_mat} />
      <mesh geometry={nodes.VH_F_neck_of_pancreas.geometry} material={materials.gland_mat} />
      <mesh geometry={nodes.VH_F_gallbladder.geometry} material={materials.Gall_mat} />
      <mesh geometry={nodes.VH_F_kidney_capsule_L.geometry} material={materials.kidney_capsule_mat} />
      <mesh geometry={nodes.VH_F_hilum_of_kidney_L.geometry} material={materials.kidney_capsule_mat} />
      <mesh geometry={nodes.VH_F_renal_papilla_L_a.geometry} material={materials.kidney_CortexMedulla_mat} />
      <mesh geometry={nodes.VH_F_renal_papilla_L_b.geometry} material={materials.kidney_CortexMedulla_mat} />
      <mesh geometry={nodes.VH_F_renal_papilla_L_c.geometry} material={materials.kidney_CortexMedulla_mat} />
      <mesh geometry={nodes.VH_F_renal_papilla_L_d.geometry} material={materials.kidney_CortexMedulla_mat} />
      <mesh geometry={nodes.VH_F_renal_papilla_L_e.geometry} material={materials.kidney_CortexMedulla_mat} />
      <mesh geometry={nodes.VH_F_renal_papilla_L_f.geometry} material={materials.kidney_CortexMedulla_mat} />
      <mesh geometry={nodes.VH_F_renal_papilla_L_g.geometry} material={materials.kidney_CortexMedulla_mat} />
      <mesh geometry={nodes.VH_F_renal_papilla_L_h.geometry} material={materials.kidney_CortexMedulla_mat} />
      <mesh geometry={nodes.VH_F_renal_papilla_L_i.geometry} material={materials.kidney_CortexMedulla_mat} />
      <mesh geometry={nodes.VH_F_renal_papilla_L_j.geometry} material={materials.kidney_CortexMedulla_mat} />
      <mesh geometry={nodes.VH_F_renal_papilla_L_k.geometry} material={materials.kidney_CortexMedulla_mat} />
      <mesh geometry={nodes.VH_F_renal_pyramid_L_a.geometry} material={materials.kidney_Pyramids_mat} />
      <mesh geometry={nodes.VH_F_renal_pyramid_L_b.geometry} material={materials.kidney_Pyramids_mat} />
      <mesh geometry={nodes.VH_F_renal_pyramid_L_c.geometry} material={materials.kidney_Pyramids_mat} />
      <mesh geometry={nodes.VH_F_renal_pyramid_L_d.geometry} material={materials.kidney_Pyramids_mat} />
      <mesh geometry={nodes.VH_F_renal_pyramid_L_e.geometry} material={materials.kidney_Pyramids_mat} />
      <mesh geometry={nodes.VH_F_renal_pyramid_L_f.geometry} material={materials.kidney_Pyramids_mat} />
      <mesh geometry={nodes.VH_F_renal_pyramid_L_g.geometry} material={materials.kidney_Pyramids_mat} />
      <mesh geometry={nodes.VH_F_renal_pyramid_L_h.geometry} material={materials.kidney_Pyramids_mat} />
      <mesh geometry={nodes.VH_F_renal_pyramid_L_i.geometry} material={materials.kidney_Pyramids_mat} />
      <mesh geometry={nodes.VH_F_renal_pyramid_L_j.geometry} material={materials.kidney_Pyramids_mat} />
      <mesh geometry={nodes.VH_F_renal_pyramid_L_k.geometry} material={materials.kidney_Pyramids_mat} />
      <mesh geometry={nodes.VH_F_renal_column_L.geometry} material={materials.kidney_CortexMedulla_mat} />
      <mesh geometry={nodes.VH_F_outer_cortex_of_kidney_L.geometry} material={materials.kidney_CortexMedulla_mat} />
      <mesh geometry={nodes.VH_F_kidney_capsule_R.geometry} material={materials.kidney_capsule_mat} />
      <mesh geometry={nodes.VH_F_hilum_of_kidney_R.geometry} material={materials.kidney_capsule_mat} />
      <mesh geometry={nodes.VH_F_outer_cortex_of_kidney_R.geometry} material={materials.kidney_CortexMedulla_mat} />
      <mesh geometry={nodes.VH_F_renal_column_R.geometry} material={materials.kidney_CortexMedulla_mat} />
      <mesh geometry={nodes.VH_F_renal_papilla_R_a.geometry} material={materials.kidney_CortexMedulla_mat} />
      <mesh geometry={nodes.VH_F_renal_papilla_R_b.geometry} material={materials.kidney_CortexMedulla_mat} />
      <mesh geometry={nodes.VH_F_renal_papilla_R_c.geometry} material={materials.kidney_CortexMedulla_mat} />
      <mesh geometry={nodes.VH_F_renal_papilla_R_d.geometry} material={materials.kidney_CortexMedulla_mat} />
      <mesh geometry={nodes.VH_F_renal_papilla_R_e.geometry} material={materials.kidney_CortexMedulla_mat} />
      <mesh geometry={nodes.VH_F_renal_papilla_R_f.geometry} material={materials.kidney_CortexMedulla_mat} />
      <mesh geometry={nodes.VH_F_renal_papilla_R_g.geometry} material={materials.kidney_CortexMedulla_mat} />
      <mesh geometry={nodes.VH_F_renal_papilla_R_h.geometry} material={materials.kidney_CortexMedulla_mat} />
      <mesh geometry={nodes.VH_F_renal_papilla_R_i.geometry} material={materials.kidney_CortexMedulla_mat} />
      <mesh geometry={nodes.VH_F_renal_papilla_R_j.geometry} material={materials.kidney_CortexMedulla_mat} />
      <mesh geometry={nodes.VH_F_renal_pyramid_R_a.geometry} material={materials.kidney_Pyramids_mat} />
      <mesh geometry={nodes.VH_F_renal_pyramid_R_b.geometry} material={materials.kidney_Pyramids_mat} />
      <mesh geometry={nodes.VH_F_renal_pyramid_R_c.geometry} material={materials.kidney_Pyramids_mat} />
      <mesh geometry={nodes.VH_F_renal_pyramid_R_d.geometry} material={materials.kidney_Pyramids_mat} />
      <mesh geometry={nodes.VH_F_renal_pyramid_R_e.geometry} material={materials.kidney_Pyramids_mat} />
      <mesh geometry={nodes.VH_F_renal_pyramid_R_f.geometry} material={materials.kidney_Pyramids_mat} />
      <mesh geometry={nodes.VH_F_renal_pyramid_R_g.geometry} material={materials.kidney_Pyramids_mat} />
      <mesh geometry={nodes.VH_F_renal_pyramid_R_h.geometry} material={materials.kidney_Pyramids_mat} />
      <mesh geometry={nodes.VH_F_renal_pyramid_R_i.geometry} material={materials.kidney_Pyramids_mat} />
      <mesh geometry={nodes.VH_F_renal_pyramid_R_j.geometry} material={materials.kidney_Pyramids_mat} />
      <mesh geometry={nodes.VH_F_renal_pelvis_R.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_right_ureter.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_minor_calyx_R_a.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_minor_calyx_R_b.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_minor_calyx_R_c.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_minor_calyx_R_d.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_minor_calyx_R_e.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_minor_calyx_R_f.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_minor_calyx_R_g.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_minor_calyx_R_h.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_minor_calyx_R_i.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_minor_calyx_R_j.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_major_calyx_R_a.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_major_calyx_R_b.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_major_calyx_R_c.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_renal_pelvis_L.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_left_ureter.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_minor_calyx_L_a.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_minor_calyx_L_b.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_minor_calyx_L_c.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_minor_calyx_L_d.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_minor_calyx_L_e.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_minor_calyx_L_f.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_minor_calyx_L_g.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_minor_calyx_L_h.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_minor_calyx_L_i.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_minor_calyx_L_j.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_major_calyx_L_a.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_major_calyx_L_b.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_major_calyx_L_c.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_major_calyx_L_d.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_fundus_of_urinary_bladder_dome.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_urinary_bladder_neck_smooth_muscle.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_fundus_of_urinary_bladder_base.geometry} material={materials.ureter_mat}>
        <mesh geometry={nodes.VH_F_trigone_of_urinary_bladder.geometry} material={materials.ureter_mat} />
        <mesh geometry={nodes.VH_F_ureteral_orifice_R.geometry} material={materials.ureter_mat} />
        <mesh geometry={nodes.VH_F_ureteral_orifice_L.geometry} material={materials.ureter_mat} />
      </mesh>
      <mesh geometry={nodes.VH_F_interventricular_septum.geometry} material={materials.heart_mat} />
      <mesh geometry={nodes.VH_F_left_cardiac_atrium.geometry} material={materials.heart_mat} />
      <mesh geometry={nodes.VH_F_left_ventricle.geometry} material={materials.heart_mat} />
      <mesh geometry={nodes.VH_F_right_cardiac_atrium.geometry} material={materials.heart_mat} />
      <mesh geometry={nodes.VH_F_right_ventricle.geometry} material={materials.heart_mat} />
      <mesh geometry={nodes.VH_F_papillary_muscle_of_heart_ant.geometry} material={materials.heart_mat} />
      <mesh geometry={nodes.VH_F_papillary_muscle_of_heart_antlat.geometry} material={materials.heart_mat} />
      <mesh geometry={nodes.VH_F_papillary_muscle_of_heart_med.geometry} material={materials.heart_mat} />
      <mesh geometry={nodes.VH_F_papillary_muscle_of_heart_pos.geometry} material={materials.heart_mat} />
      <mesh geometry={nodes.VH_F_papillary_muscle_of_heart_posmed.geometry} material={materials.heart_mat} />
      <mesh geometry={nodes.VH_F_aortic_valve.geometry} material={materials.heart_mat} />
      <mesh geometry={nodes.VH_F_pulmonary_valve.geometry} material={materials.heart_mat} />
      <mesh geometry={nodes.VH_F_mitral_valve.geometry} material={materials.heart_mat} />
      <mesh geometry={nodes.VH_F_tricuspid_valve.geometry} material={materials.heart_mat} />
      <mesh geometry={nodes.VH_F_left_uterine_artery.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_right_uterine_artery.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_left_uterine_vein.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_right_uterine_vein.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_ophthalmic_vein_L.geometry} material={materials['eye_edits_012024:pasted__vein_mat']} />
      <mesh geometry={nodes.VH_F_superior_ophthalmic_vein_L.geometry} material={materials['eye_edits_012024:pasted__vein_mat']} />
      <mesh geometry={nodes.VH_F_inferior_ophthalmic_vein_L.geometry} material={materials['eye_edits_012024:pasted__vein_mat']} />
      <mesh geometry={nodes.VH_F_central_retinal_vein_L.geometry} material={materials['eye_edits_012024:pasted__vein_mat']} />
      <mesh geometry={nodes.VH_F_ophthalmic_vein_R.geometry} material={materials['eye_edits_012022:pasted__vein_mat']} />
      <mesh geometry={nodes.VH_F_superior_ophthalmic_vein_R.geometry} material={materials['eye_edits_012022:pasted__vein_mat']} />
      <mesh geometry={nodes.VH_F_inferior_ophthalmic_vein_R.geometry} material={materials['eye_edits_012022:pasted__vein_mat']} />
      <mesh geometry={nodes.VH_F_central_retinal_vein_R.geometry} material={materials['eye_edits_012022:pasted__vein_mat']} />
      <mesh geometry={nodes.VH_F_long_posterior_ciliary_artery_L.geometry} material={materials.pasted__pasted__pasted__dura_mater_mat} />
      <mesh geometry={nodes.VH_F_opthalmic_artery_L.geometry} material={materials['eye_edits_012024:pasted__artery_mat']} />
      <mesh geometry={nodes.VH_F_central_retinal_artery_L.geometry} material={materials['eye_edits_012024:pasted__artery_mat']} />
      <mesh geometry={nodes.VH_F_long_posterior_ciliary_artery_R.geometry} material={materials.pasted__pasted__dura_mater_mat} />
      <mesh geometry={nodes.VH_F_opthalmic_artery_R.geometry} material={materials['eye_edits_012022:pasted__artery_mat']} />
      <mesh geometry={nodes.VH_F_central_retinal_artery_R.geometry} material={materials['eye_edits_012022:pasted__artery_mat']} />
      <mesh geometry={nodes.VH_F_right_renal_artery.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_left_renal_artery.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_left_renal_vein.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_right_renal_vein.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_superior_mesenteric_vein.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_superior_rectal_vein.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_left_colic_vein.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_right_colic_vein.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_ileocolic_vein.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_middle_colic_vein.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_median_sacral_vein.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_sigmoid_vein_b.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_inferior_pancreaticoduodenal_vein.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_inferior_mesenteric_vein.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_left_common_iliac_vein.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_right_common_iliac_vein.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_inferior_rectal_vein_L.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_inferior_rectal_vein_R.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_internal_iliac_vein_L.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_internal_iliac_vein_R.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_internal_pudendal_vein_L.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_internal_pudendal_vein_R.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_middle_rectal_vein_L.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_middle_rectal_vein_R.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_sigmoid_vein_a.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_sigmoid_vein_c.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_left_colic_artery.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_right_colic_artery.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_ileocolic_artery.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_middle_colic_artery.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_celiac_trunk.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_superior_rectal_artery.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_superior_mesenteric_artery.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_inferior_mesenteric_artery.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_marginal_artery_of_Drummond.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_sigmoid_artery_c.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_sigmoid_artery_b.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_sigmoid_artery_a.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_splenic_artery.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_splenic_vein.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_cystic_artery.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_cystic_vein.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_middle_hepatic_artery_branch_of_left_hepatic_artery.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_proper_hepatic_artery.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_right_hepatic_artery.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_common_hepatic_artery.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_posterior_segmental_right_hepatic_artery.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_anterior_segmental_right_hepatic_artery.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_left_hepatic_artery.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_hepatic_portal_vein.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_middle_hepatic_vein.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_left_hepatic_vein.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_right_hepatic_vein.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_right_branch_of_portal_vein.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_left_branch_of_portal_vein.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_pulmonary_vein_L_sup.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_pulmonary_vein_R_inf.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_pulmonary_vein_R_sup.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_pulmonary_vein_L_inf.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_coronary_sinus.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_great_cardiac_vein.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_middle_cardiac_vein.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_oblique_vein_of_left_atrium.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_left_marginal_vein.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_posterior_vein_of_left_ventricle.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_anterior_cardiac_vein.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_small_cardiac_vein.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_superior_vena_cava.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_inferior_vena_cava_a.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_inferior_vena_cava_b.geometry} material={materials.Vein_mat} />
      <mesh geometry={nodes.VH_F_left_anterior_descending_artery.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_left_circumflex_artery.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_diagonal_branch_of_left_anterior_descending_artery.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_left_coronary_artery.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_left_marginal_branch.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_left_posterior_descending_branch_of_circumflex_branch_of_left_coronary_artery.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_posterior_left_ventricular_branch.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_right_coronary_artery.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_right_marginal_artery.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_pulmonary_artery_L.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_pulmonary_trunk.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_pulmonary_artery_R.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_aortic_arch.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_ascending_aorta.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_brachiocephalic_artery_b.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_brachiocephalic_artery_a.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_descending_aorta_a.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_descending_aorta_b.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_left_common_carotid_artery_a.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_left_common_carotid_artery_b.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_left_subclavian_artery_a.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_left_subclavian_artery_b.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_hilum_L.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_F_hilum_upper_L.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_F_lingula_superior_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_F_left_anterior_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_F_left_apical_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_F_left_posterior_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_F_lingula_inferior_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_F_left_superior_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_F_left_posterior_basal_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_F_left_anterior_basal_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_F_left_lateral_basal_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_F_left_medial_basal_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_F_hilum_lower_L.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_F_hilum_R.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_F_right_medial_basal_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_F_right_posterior_basal_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_F_right_anterior_basal_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_F_right_lateral_basal_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_F_right_superior_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_F_hilum_lower_R.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_F_right_medial_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_F_right_lateral_bronchopulmonary_segmennt.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_F_hilum_middle_R.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_F_right_anterior_bronchopulmonary_segm.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_F_right_apical_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_F_right_posterior_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_F_hilum_upper_R.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_F_epiglotic_cartilage.geometry} material={materials.cartilage_mat} />
      <mesh geometry={nodes.VH_F_cricoid_cartilage.geometry} material={materials.cartilage_mat} />
      <mesh geometry={nodes.VH_F_thyroid_cartilage.geometry} material={materials.cartilage_mat} />
      <mesh geometry={nodes.VH_F_arytenoid_cartilage_R.geometry} material={materials.cartilage_mat} />
      <mesh geometry={nodes.VH_F_arytenoid_cartilage_L.geometry} material={materials.cartilage_mat} />
      <mesh geometry={nodes.VH_F_corniculate_cartilage_L.geometry} material={materials.cartilage_mat} />
      <mesh geometry={nodes.VH_F_corniculate_cartilage_R.geometry} material={materials.cartilage_mat} />
      <mesh geometry={nodes.VH_F_trachea.geometry} material={materials.mucosa_mat}>
        <mesh geometry={nodes.VH_F_tracheal_cartilage.geometry} material={materials.cartilage_mat} />
        <mesh geometry={nodes.VH_F_carina.geometry} material={materials.cartilage_mat} />
      </mesh>
      <mesh geometry={nodes.VH_F_right_main_bronchus.geometry} material={materials.mucosa_mat}>
        <mesh geometry={nodes.VH_F_cartilage_of_main_bronchus_R.geometry} material={materials.VH_F_R_main_bronchus_bronchial_cartilage_ncl1_2} />
      </mesh>
      <mesh geometry={nodes.VH_F_left_main_bronchus.geometry} material={materials.mucosa_mat}>
        <mesh geometry={nodes.VH_F_cartilage_of_main_bronchus_L.geometry} material={materials.VH_F_L_main_bronchus_bronchial_cartilage_ncl1_2} />
      </mesh>
      <mesh geometry={nodes.VH_F_cartilage_of_lobar_bronchus_L.geometry} material={materials.VH_F_L_lobar_bronchial_cartilage_ncl1_2} />
      <mesh geometry={nodes.VH_F_cartilage_of_tertiary_bronchus_L.geometry} material={materials.VH_F_L_tertiary_bronchial_cartilage_ncl1_2} />
      <mesh geometry={nodes.VH_F_left_superior_lobar_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_F_left_inferior_lobar_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_F_left_anterior_basal_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_F_left_lingula_superior_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_F_left_apical_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_F_left_posterior_basal_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_F_left_medial_basal_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_F_left_superior_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_F_left_anterior_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_F_left_posterior_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_F_left_lateral_basal_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_F_left_lingula_inferior_bronchi.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_F_cartilage_of_lobar_bronchus_R.geometry} material={materials.VH_F_R_lobar_bronchial_cartilage_ncl1_2} />
      <mesh geometry={nodes.VH_F_cartilage_of_tertiary_bronchus_R.geometry} material={materials.VH_F_R_tertiary_bronchial_cartilage_ncl1_2} />
      <mesh geometry={nodes.VH_F_right_middle_lobar_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_F_right_superior_lobar_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_F_right_inferior_lobar_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_F_right_anterior_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_F_right_lateral_basal_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_F_right_lateral_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_F_right_medial_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_F_right_medial_basal_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_F_right_posterior_basal_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_F_right_posterior_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_F_right_superior_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_F_right_apical_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_F_right_anterior_basal_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_F_gastric_surface_of_spleen.geometry} material={materials.spleen_mat} />
      <mesh geometry={nodes.VH_F_diaphragmatic_surface_of_spleen.geometry} material={materials.spleen_mat} />
      <mesh geometry={nodes.VH_F_colic_surface_of_spleen.geometry} material={materials.spleen_mat} />
      <mesh geometry={nodes.VH_F_hilum_of_spleen.geometry} material={materials.spleen_mat} />
      <mesh geometry={nodes.VH_F_renal_surface_of_spleen.geometry} material={materials.spleen_mat} />
      <mesh geometry={nodes.VH_F_thymus_lobe_L.geometry} material={materials.gland_mat} />
      <mesh geometry={nodes.VH_F_thymus_lobe_R.geometry} material={materials.gland_mat} />
      <mesh geometry={nodes.Yao_afferent_lymphatic_vessel.geometry} material={materials.lymph_mat} />
      <mesh geometry={nodes.Yao_capsule_of_lymph_node.geometry} material={materials.lymph_mat} />
      <mesh geometry={nodes.Yao_follicles.geometry} material={materials.lymph_cortex_mat} />
      <mesh geometry={nodes.Yao_efferent_lymph_node.geometry} material={materials.lymph_mat} />
      <mesh geometry={nodes.Yao_medulla_of_lymph_node.geometry} material={materials.lymph_medulla_mat} />
      <mesh geometry={nodes.Yao_paracortex.geometry} material={materials.lymph_paracortex_mat} />
      <mesh geometry={nodes.Yao_blood_vasculature.geometry} material={materials.Arteries_Mat} />
      <mesh geometry={nodes.VH_F_sacrum.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_F_coccyx.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_F_pubis_spongy_bone_L.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_F_pubis_spongy_bone_R.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_F_pubis_compact_bone_R.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_F_pubis_compact_bone_L.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_F_ilium_compact_bone_R.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_F_ilium_compact_bone_L.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_F_ilium_spongy_bone_L.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_F_ilium_spongy_bone_R.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_F_ischium_compact_bone_R.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_F_ischium_compact_bone_L.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_F_ischium_spongy_bone_R.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_F_ischium_spongy_bone_L.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_F_right_tibial_collateral_ligament.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_anterior_cruciate_ligament_of_knee_R.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_posterior_cruciate_ligament_of_knee_R.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_anterolateral_ligament_of_knee_R.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_fibular_collateral_ligament_R.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_patellar_ligament_R.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_meniscus_R.geometry} material={materials.meniscus_mat} />
      <mesh geometry={nodes.VH_F_femur_R.geometry} material={materials.Bone_Mat}>
        <mesh geometry={nodes.VH_F_trochlear_groove_R.geometry} material={materials.Bone_Mat} />
        <mesh geometry={nodes.VH_F_medial_perichondular_surface_R.geometry} material={materials.Bone_Mat} />
        <mesh geometry={nodes.VH_F_articular_cartilage_of_knee_R.geometry} material={materials.Bone_Mat}>
          <mesh geometry={nodes.VH_F_medial_condyle_of_right_femur_sup.geometry} material={materials.Bone_Mat} />
          <mesh geometry={nodes.VH_F_lateral_condyle_of_femur_sup_R.geometry} material={materials.Bone_Mat} />
          <mesh geometry={nodes.VH_F_medial_condyle_of_right_femur_inf.geometry} material={materials.Bone_Mat} />
          <mesh geometry={nodes.VH_F_lateral_condyle_of_femur_inf_R.geometry} material={materials.Bone_Mat} />
          <mesh geometry={nodes.VH_F_lateral_condyle_of_femur_frontal_R.geometry} material={materials.Bone_Mat} />
          <mesh geometry={nodes.VH_F_distal_most_point_of_medial_condyle_R.geometry} material={materials.Bone_Mat} />
        </mesh>
        <mesh geometry={nodes.VH_F_intercondylar_fossa_R.geometry} material={materials.Bone_Mat}>
          <mesh geometry={nodes.VH_F_posterior_cruciate_enthesis_R.geometry} material={materials.Bone_Mat} />
          <mesh geometry={nodes.VH_F_anterior_cruciate_enthesis_R.geometry} material={materials.Bone_Mat} />
        </mesh>
        <mesh geometry={nodes.VH_F_lateral_perichondular_surface_R.geometry} material={materials.Bone_Mat} />
        <mesh geometry={nodes.VH_F_lateral_epicondylar_enthesis_R.geometry} material={materials.Bone_Mat} />
        <mesh geometry={nodes.VH_F_medial_epicondylar_enthesis_R.geometry} material={materials.Bone_Mat} />
      </mesh>
      <mesh geometry={nodes.VH_F_tibia_R.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_F_fibula_R.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_F_patella_R.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_F_anterolateral_ligament_of_knee_L.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_fibular_collateral_ligament_L.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_patellar_ligament_L.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_left_tibial_collateral_ligament.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_anterior_cruciate_ligament_of_knee_L.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_posterior_cruciate_ligament_of_knee_L.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_F_meniscus_L.geometry} material={materials.meniscus_mat} />
      <mesh geometry={nodes.VH_F_femur_L.geometry} material={materials.Bone_Mat}>
        <mesh geometry={nodes.VH_F_intercondylar_fossa_L.geometry} material={materials.Bone_Mat}>
          <mesh geometry={nodes.VH_F_anterior_cruciate_enthesis_L.geometry} material={materials.Bone_Mat} />
          <mesh geometry={nodes.VH_F_posterior_cruciate_enthesis_L.geometry} material={materials.Bone_Mat} />
        </mesh>
        <mesh geometry={nodes.VH_F_lateral_perichondular_surface_L.geometry} material={materials.Bone_Mat} />
        <mesh geometry={nodes.VH_F_lateral_epicondylar_enthesis_L.geometry} material={materials.Bone_Mat} />
        <mesh geometry={nodes.VH_F_medial_epicondylar_enthesis_L.geometry} material={materials.Bone_Mat} />
        <mesh geometry={nodes.VH_F_trochlear_groove_L.geometry} material={materials.Bone_Mat} />
        <mesh geometry={nodes.VH_F_medial_perichondular_surface_L.geometry} material={materials.Bone_Mat} />
        <mesh geometry={nodes.VH_F_articular_cartilage_of_knee_L.geometry} material={materials.Bone_Mat}>
          <mesh geometry={nodes.VH_F_medial_condyle_of_left_femur_inf.geometry} material={materials.Bone_Mat} />
          <mesh geometry={nodes.VH_F_lateral_condyle_of_femur_inf_L.geometry} material={materials.Bone_Mat} />
          <mesh geometry={nodes.VH_F_lateral_condyle_of_femur_frontal_L.geometry} material={materials.Bone_Mat} />
          <mesh geometry={nodes.VH_F_distal_most_point_of_medial_condyle_L.geometry} material={materials.Bone_Mat} />
          <mesh geometry={nodes.VH_F_lateral_condyle_of_femur_sup_L.geometry} material={materials.Bone_Mat} />
          <mesh geometry={nodes.VH_F_medial_condyle_of_left_femur_sup.geometry} material={materials.Bone_Mat} />
        </mesh>
      </mesh>
      <mesh geometry={nodes.VH_F_patella_L.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_F_tibia_L.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_F_fibula_L.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_F_lumbar_vertebra_1.geometry} material={materials.pasted__Bone_Mat3} />
      <mesh geometry={nodes.VH_F_lumbar_vertebra_2.geometry} material={materials.pasted__Bone_Mat3} />
      <mesh geometry={nodes.VH_F_lumbar_vertebra_3.geometry} material={materials.pasted__Bone_Mat3} />
      <mesh geometry={nodes.VH_F_lumbar_vertebra_4.geometry} material={materials.pasted__Bone_Mat3} />
      <mesh geometry={nodes.VH_F_lumbar_vertebra_5.geometry} material={materials.pasted__Bone_Mat3} />
      <mesh geometry={nodes.VH_F_lumbar_vertebra_6.geometry} material={materials.pasted__Bone_Mat3} />
      <mesh geometry={nodes.VH_F_thoracic_vertebra_1.geometry} material={materials.pasted__Bone_Mat3} />
      <mesh geometry={nodes.VH_F_thoracic_vertebra_2.geometry} material={materials.pasted__Bone_Mat3} />
      <mesh geometry={nodes.VH_F_thoracic_vertebra_3.geometry} material={materials.pasted__Bone_Mat3} />
      <mesh geometry={nodes.VH_F_thoracic_vertebra_4.geometry} material={materials.pasted__Bone_Mat3} />
      <mesh geometry={nodes.VH_F_thoracic_vertebra_5.geometry} material={materials.pasted__Bone_Mat3} />
      <mesh geometry={nodes.VH_F_thoracic_vertebra_6.geometry} material={materials.pasted__Bone_Mat3} />
      <mesh geometry={nodes.VH_F_thoracic_vertebra_7.geometry} material={materials.pasted__Bone_Mat3} />
      <mesh geometry={nodes.VH_F_thoracic_vertebra_8.geometry} material={materials.pasted__Bone_Mat3} />
      <mesh geometry={nodes.VH_F_thoracic_vertebra_9.geometry} material={materials.pasted__Bone_Mat3} />
      <mesh geometry={nodes.VH_F_thoracic_vertebra_10.geometry} material={materials.pasted__Bone_Mat3} />
      <mesh geometry={nodes.VH_F_thoracic_vertebra_11.geometry} material={materials.pasted__Bone_Mat3} />
      <mesh geometry={nodes.VH_F_thoracic_vertebra_12.geometry} material={materials.pasted__Bone_Mat3} />
      <mesh geometry={nodes.VH_F_cervical_vertebra_1.geometry} material={materials.pasted__Bone_Mat3} />
      <mesh geometry={nodes.VH_F_cervical_vertebra_2.geometry} material={materials.pasted__Bone_Mat3} />
      <mesh geometry={nodes.VH_F_cervical_vertebra_3.geometry} material={materials.pasted__Bone_Mat3} />
      <mesh geometry={nodes.VH_F_cervical_vertebra_4.geometry} material={materials.pasted__Bone_Mat3} />
      <mesh geometry={nodes.VH_F_cervical_vertebra_5.geometry} material={materials.pasted__Bone_Mat3} />
      <mesh geometry={nodes.VH_F_cervical_vertebra_6.geometry} material={materials.pasted__Bone_Mat3} />
      <mesh geometry={nodes.VH_F_cervical_vertebra_7.geometry} material={materials.pasted__Bone_Mat3} />
    </group>
  )
}

useGLTF.preload('/fanatomy-opt.glb', 'https://www.gstatic.com/draco/versioned/decoders/1.5.5/')
