/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/anatomy.glb -o src/components/Dashboard/AnatomyModel.jsx 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

export function Model({ organStress, ...props }) {
  // Use Draco decoder for compressed models
  const { nodes, materials } = useGLTF('/anatomy-opt.glb', 'https://www.gstatic.com/draco/versioned/decoders/1.5.5/')
  
  // Mapping of organ keys to their materials in the GLB
  const organMap = {
    heart: [materials.heart_mat],
    lungs: [materials.lung_mat],
    brain: [materials.brain_mat],
    liver: [materials.Liver_Mat],
    kidneys: [materials.kidneycortex_medulla_mat, materials.kidney_pyramids_mat],
    pancreas: [materials.Gland_Mat]
  };

  const getTargetColor = (organ, stress) => {
    let colorHex = 0xffffff;
    switch(organ) {
      case 'lungs':
        if (stress > 60) colorHex = 0x2b2b2b;
        else if (stress > 25) colorHex = 0x696969;
        else colorHex = 0xffb6c1;
        break;
      case 'liver':
        if (stress > 60) colorHex = 0x4a2e15;
        else if (stress > 25) colorHex = 0xc2b280;
        else colorHex = 0x8b3a3a;
        break;
      case 'heart':
        if (stress > 60) colorHex = 0x4a0e17;
        else if (stress > 25) colorHex = 0x8b0000;
        else colorHex = 0xdc143c;
        break;
      case 'brain':
        if (stress > 60) colorHex = 0x808080;
        else if (stress > 25) colorHex = 0xe6e6a1;
        else colorHex = 0xffe4e1;
        break;
      case 'pancreas':
        if (stress > 60) colorHex = 0x654321;
        else if (stress > 25) colorHex = 0xff8c00;
        else colorHex = 0xffb6c1;
        break;
      case 'kidneys':
        if (stress > 60) colorHex = 0x2a1b15;
        else if (stress > 25) colorHex = 0x5c3317;
        else colorHex = 0xa52a2a;
        break;
      default:
        colorHex = 0xffffff;
    }
    return new THREE.Color(colorHex);
  };

  // Animation and realistic color transitions
  useFrame((state, delta) => {
    const stressState = organStress || {};
    Object.entries(organMap).forEach(([key, mats]) => {
      const stress = stressState[key] || 0;
      const targetColor = getTargetColor(key, stress);
      
      mats.forEach(mat => {
        if (!mat) return;
        
        if (!mat.color) mat.color = new THREE.Color(0xffffff);
        
        // Smoothly interpolate base color
        mat.color.lerp(targetColor, delta * 2.0);
        
        // Keep emissive extremely subtle to mimic moisture/highlights, not neon glowing
        mat.emissive.copy(targetColor);
        mat.emissiveIntensity = stress > 25 ? 0.1 : 0; 
      });
    });
  });

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.VH_M_skin.geometry} material={materials.pasted__Skin_Mat} />
      <mesh geometry={nodes.VH_M_C1_segment_of_cervical_spinal_cord.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_C2_segment_of_cervical_spinal_cord.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_C3_segment_of_cervical_spinal_cord.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_C4_segment_of_cervical_spinal_cord.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_C5_segment_of_cervical_spinal_cord.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_C6_segment_of_cervical_spinal_cord.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_C7_segment_of_cervical_spinal_cord.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_C8_segment_of_cervical_spinal_cord.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_first_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_second_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_third_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_fourth_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_fifth_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_sixth_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_seventh_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_eighth_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_ninth_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_tenth_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_eleventh_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_twelfth_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_first_lumbar_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_second_lumbar_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_third_lumbar_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_fourth_lumbar_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_fifth_lumbar_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_first_sacral_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_second_sacral_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_third_sacral_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_fourth_sacral_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_fifth_sacral_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh geometry={nodes.VH_M_optic_chiasm.geometry} material={materials.retina} />
      <mesh geometry={nodes.Allen_olfactory_bulb_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_anterior_olfactory_nucleus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_piriform_region_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_frontal_agranular_insular_cortex_area_Fl_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_temporal_agranular_insular_cortex_area_Tl_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_head_of_caudate_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_body_of_caudate_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_tail_of_caudate_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_putamen_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_nucleus_accumbens_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_external_segment_of_globus_pallidus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_internal_segment_of_globus_pallidus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_claustrum_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_basal_forebrain_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_septal_nuclei_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_amygdaloid_complex_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_anterior_amygdaloid_area_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_central_nuclear_group_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_lateral_nucleus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_basolateral_nucleus_basal_nucleus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_basomedial_nucleus_accessory_basal_nucleus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_anterior_cortical_nucleus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_posterior_cortical_nucleus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_medial_nucleus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_amygdalohippocampal_area_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_bed_nucleus_of_stria_terminalis_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_thalamus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_anterior_nuclear_complex_of_thalamus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_lateral_dorsal_nucleus_of_thalamus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_mediodorsal_nucleus_of_thalamus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_reuniens_nucleus_medioventral_nucleus_of_thalamus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_lateral_posterior_nucleus_of_thalamus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_pulvinar_of_thalamus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_ventral_anterior_nucleus_of_thalamus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_ventral_lateral_nucleus_of_thalamus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_ventral_posterior_lateral_nucleus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_ventral_posterior_medial_nucleus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_dorsal_lateral_geniculate_nucleus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_medial_geniculate_nuclei_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_centromedian_nucleus_of_thalamus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_parafascicular_nucleus_of_thalamus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_habenular_nuclei_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_pineal_body_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_zona_incerta_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_supraoptic_region_of_HTH_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_preoptic_region_of_HTH_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_tuberal_region_of_HTH_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_white_matter_of_forebrain_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_anterior_commissure_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_corpus_callosum_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_fornix_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_mammillothalamic_tract_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_optic_tract_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_anterior_horn_of_lateral_ventricle_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_body_of_lateral_ventricle_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_posterior_horn_of_lateral_ventricle_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_inferior_horn_of_lateral_ventricle_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_third_ventricle_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_cerebellar_vermis_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_cerebellar_deep_nuclei_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_white_matter_of_hindbrain_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_olfactory_tract_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_precentral_gyrus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_superior_frontal_gyrus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_middle_frontal_gyrus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_inferior_frontal_gyrus_triangular_part_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_inferior_frontal_gyrus_opercular_part_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_gyrus_rectus_straight_gyrus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_medial_orbital_gyrus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_anterior_intermediate_orbital_gyrus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_posterior_intermediate_orbital_gyrus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_lateral_orbital_gyrus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_paracentral_lobule_rostral_part_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_frontal_operculum_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_postcentral_gyrus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_supraparietal_lobule_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_supramarginal_gyrus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_angular_gyrus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_precuneus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_paracentral_lobule_caudal_part_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_superior_temporal_gyrus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_middle_temporal_gyrus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_inferior_temporal_gyrus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_occipitotemporal_fusiform_gyrus_temporal_part_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_transverse_temporal_gyrus_Heschls_gyrus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_planum_temporale_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_temporal_pole_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_planum_polare_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_occipital_pole_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_cuneus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_lingual_gyrus_medial_occipitotemporal_gyrus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_lateral_occipitotemporal_fusiform_gyrus_occipital_part_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_inferior_occipital_gyrus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_superior_occipital_gyrus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_cingulate_gyrus_rostral_anterior_part_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_cingulate_gyrus_caudal_posterior_part_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_ingulo_parahippocampal_isthmus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_subcallosal_gyrus_parolfactory_gyrus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_anterior_parahippocampal_gyrus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_posterior_parahippocampal_gyrus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_gyrus_ambiens_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_head_of_hippocampus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_body_of_hippocampus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_tail_of_hippocampus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_long_insular_gyri_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_short_insular_gyri_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_limen_insula_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_pretectal_region_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_substantia_nigra_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_superior_colliculus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_cerebral_peduncle_crus_cerebri_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_superior_cerebellar_peduncle_brachium_conjunctivum_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_cerebral_aqueduct_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_paravermis_of_cerebellum_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_lateral_hemisphere_of_cerebellum_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_basilar_part_of_pons_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_pontine_tegmentum_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_pyramidal_part_of_medulla_oblongata_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_tegmentum_of_medulla_oblongata_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_inferior_olive_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_middle_cerebellar_peduncle_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_fourth_ventricle_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_central_canal_of_medulla_oblongata_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_midline_nuclear_complex_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_lateral_olfactory_gyrus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_parietal_operculum_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_optic_radiation_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_posteroventral_putamen_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_atrium_of_lateral_ventricle_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_paracingulate_gyrus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_rostral_gyrus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_frontomarginal_gyrus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_frontal_pole_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_inferior_cerebellar_peduncle_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_perirhinal_gyrus_rostral_part_of_FuGt_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_olfactory_bulb_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_anterior_olfactory_nucleus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_piriform_region_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_frontal_agranular_insular_cortex_area_Fl_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_temporal_agranular_insular_cortex_area_Tl_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_head_of_caudate_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_body_of_caudate_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_tail_of_caudate_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_putamen_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_nucleus_accumbens_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_external_segment_of_globus_pallidus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_internal_segment_of_globus_pallidus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_claustrum_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_basal_forebrain_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_septal_nuclei_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_amygdaloid_complex_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_anterior_amygdaloid_area_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_central_nuclear_group_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_lateral_nucleus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_basolateral_nucleus_basal_nucleus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_basomedial_nucleus_accessory_basal_nucleus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_anterior_cortical_nucleus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_posterior_cortical_nucleus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_medial_nucleus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_amygdalohippocampal_area_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_bed_nucleus_of_stria_terminalis_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_thalamus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_anterior_nuclear_complex_of_thalamus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_lateral_dorsal_nucleus_of_thalamus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_mediodorsal_nucleus_of_thalamus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_reuniens_nucleus_medioventral_nucleus_of_thalamus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_lateral_posterior_nucleus_of_thalamus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_pulvinar_of_thalamus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_ventral_anterior_nucleus_of_thalamus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_ventral_lateral_nucleus_of_thalamus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_ventral_posterior_lateral_nucleus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_ventral_posterior_medial_nucleus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_dorsal_lateral_geniculate_nucleus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_medial_geniculate_nuclei_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_centromedian_nucleus_of_thalamus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_parafascicular_nucleus_of_thalamus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_habenular_nuclei_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_pineal_body_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_zona_incerta_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_supraoptic_region_of_HTH_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_white_matter_of_forebrain_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_anterior_commissure_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_corpus_callosum_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_fornix_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_mammillothalamic_tract_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_optic_tract_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_anterior_horn_of_lateral_ventricle_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_body_of_lateral_ventricle_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_posterior_horn_of_lateral_ventricle_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_inferior_horn_of_lateral_ventricle_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_third_ventricle_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_cerebellar_vermis_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_cerebellar_deep_nuclei_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_white_matter_of_hindbrain_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_olfactory_tract_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_precentral_gyrus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_superior_frontal_gyrus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_middle_frontal_gyrus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_inferior_frontal_gyrus_triangular_part_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_inferior_frontal_gyrus_opercular_part_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_gyrus_rectus_straight_gyrus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_medial_orbital_gyrus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_anterior_intermediate_orbital_gyrus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_posterior_intermediate_orbital_gyrus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_lateral_orbital_gyrus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_paracentral_lobule_rostral_part_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_frontal_operculum_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_postcentral_gyrus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_supraparietal_lobule_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_supramarginal_gyrus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_angular_gyrus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_precuneus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_paracentral_lobule_caudal_part_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_superior_temporal_gyrus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_middle_temporal_gyrus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_inferior_temporal_gyrus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_occipitotemporal_fusiform_gyrus_temporal_part_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_transverse_temporal_gyrus_Heschls_gyrus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_planum_temporale_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_temporal_pole_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_planum_polare_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_occipital_pole_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_cuneus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_lingual_gyrus_medial_occipitotemporal_gyrus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_lateral_occipitotemporal_fusiform_gyrus_occipital_part_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_inferior_occipital_gyrus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_superior_occipital_gyrus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_cingulate_gyrus_rostral_anterior_part_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_cingulate_gyrus_caudal_posterior_part_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_ingulo_parahippocampal_isthmus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_subcallosal_gyrus_parolfactory_gyrus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_anterior_parahippocampal_gyrus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_posterior_parahippocampal_gyrus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_gyrus_ambiens_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_head_of_hippocampus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_body_of_hippocampus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_tail_of_hippocampus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_long_insular_gyri_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_short_insular_gyri_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_limen_insula_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_pretectal_region_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_red_nucleus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_substantia_nigra_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_superior_colliculus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_inferior_colliculus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_cerebral_peduncle_crus_cerebri_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_superior_cerebellar_peduncle_brachium_conjunctivum_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_cerebral_aqueduct_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_paravermis_of_cerebellum_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_lateral_hemisphere_of_cerebellum_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_basilar_part_of_pons_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_pontine_tegmentum_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_pyramidal_part_of_medulla_oblongata_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_tegmentum_of_medulla_oblongata_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_inferior_olive_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_inferior_cerebellar_peduncle_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_middle_cerebellar_peduncle_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_fourth_ventricle_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_central_canal_of_medulla_oblongata_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_midline_nuclear_complex_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_lateral_olfactory_gyrus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_parietal_operculum_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_optic_radiation_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_posteroventral_putamen_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_atrium_of_lateral_ventricle_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_paracingulate_gyrus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_rostral_gyrus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_frontomarginal_gyrus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_frontal_pole_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_perirhinal_gyrus_rostral_part_of_FuGt_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_hypothalamus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_hypothalamus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_subthalamic_nucleus_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_mammillary_region_of_HTH_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_midbrain_tegmentum_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_tuberal_region_of_HTH_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_preoptic_region_of_HTH_R.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_midbrain_tegmentum_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_red_nucleus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_inferior_colliculus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_mammillary_region_of_HTH_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.Allen_subthalamic_nucleus_L.geometry} material={materials.brain_mat} />
      <mesh geometry={nodes.VH_M_dura_mater_left.geometry} material={materials.pasted__pasted__dura_mater_mat} />
      <mesh geometry={nodes.VH_M_left_optic_nerve.geometry} material={materials['eye_edits_012024:pasted__retina3']} />
      <mesh geometry={nodes.VH_M_dura_mater_right.geometry} material={materials.pasted__dura_mater_mat} />
      <mesh geometry={nodes.VH_M_right_optic_nerve.geometry} material={materials['eye_edits_012022:pasted__retina3']} />
      <mesh geometry={nodes.VH_M_retina_R.geometry} material={materials['eye_edits_012042:retina1']}>
        <mesh geometry={nodes.VH_M_fovea_R.geometry} material={materials['eye_edits_012043:fovea_mat']} />
        <mesh geometry={nodes.VH_M_macula_lutea_R.geometry} material={materials['eye_edits_012043:macula']} />
        <mesh geometry={nodes.VH_M_optic_disc_R.geometry} material={materials['eye_edits_012042:pasted__retina3']} />
      </mesh>
      <mesh geometry={nodes.VH_M_sclera_R.geometry} material={materials['eye_edits_012042:Eyeball_Mat']} />
      <mesh geometry={nodes.VH_M_optic_choroid_R.geometry} material={materials['eye_edits_012043:choroid_mat']} />
      <mesh geometry={nodes.VH_M_pupil_R.geometry} material={materials['eye_edits_012042:pupil1']} />
      <mesh geometry={nodes.VH_M_ciliary_processes_R.geometry} material={materials['eye_edits_012043:brain_mat1']} />
      <mesh geometry={nodes.VH_M_suspensory_ligament_of_lens_R.geometry} material={materials['eye_edits_012043:iris_mat']} />
      <mesh geometry={nodes.VH_M_ora_serrata_of_retina_R.geometry} material={materials['eye_edits_012043:Ora_serrata_Mat']} />
      <mesh geometry={nodes.VH_M_corneo_scleral_junction_R.geometry} material={materials['eye_edits_012043:limbus1']} />
      <mesh geometry={nodes.VH_M_lens_R.geometry} material={materials['eye_edits_012042:lens1']} />
      <mesh geometry={nodes.VH_M_schlemms_canal_R.geometry} material={materials['eye_edits_012043:Skin_Mat']} />
      <mesh geometry={nodes.VH_M_aqueous_humor_R.geometry} material={materials['eye_edits_012042:humor_mat']} />
      <mesh geometry={nodes.VH_M_ciliary_body_R.geometry} material={materials['eye_edits_012044:lung_mat']}>
        <mesh geometry={nodes.VH_M_ciliary_muscle_R.geometry} material={materials['eye_edits_012045:lung_mat']} />
      </mesh>
      <mesh geometry={nodes.VH_M_trabecular_meshwork_R.geometry} material={materials['eye_edits_012043:meniscus_mat']} />
      <mesh geometry={nodes.VH_M_iris_R.geometry} material={materials['eye_edits_012042:iris_mat']} />
      <mesh geometry={nodes.VH_M_bulbar_conjunctiva_R.geometry} material={materials['eye_edits_012042:Bone_Mat']} />
      <mesh geometry={nodes.VH_M_cornea_R.geometry} material={materials['eye_edits_012042:Cornea_mat']} />
      <mesh geometry={nodes.VH_M_vitreous_humor_R.geometry} material={materials['eye_edits_012042:humor_mat']} />
      <mesh geometry={nodes.VH_M_palpebral_conjunctiva_of_upper_eyelid_R.geometry} material={materials.pasted__pasted__pasted__pasted__conjunctiva_Mat1} />
      <mesh geometry={nodes.VH_M_palpebral_conjunctiva_of_lower_eyelid_R.geometry} material={materials.pasted__pasted__pasted__pasted__conjunctiva_Mat1} />
      <mesh geometry={nodes.VH_M_retina_L.geometry} material={materials.pasted__retina_mat}>
        <mesh geometry={nodes.VH_M_fovea_L.geometry} material={materials.pasted__fovea_mat} />
        <mesh geometry={nodes.VH_M_macula_lutea_L.geometry} material={materials.pasted__macula_mat} />
        <mesh geometry={nodes.VH_M_optic_disc_L.geometry} material={materials.pasted__retina_mat} />
      </mesh>
      <mesh geometry={nodes.VH_M_vitreous_humor_L.geometry} material={materials['eye_edits_012042:humor_mat']} />
      <mesh geometry={nodes.VH_M_cornea_L.geometry} material={materials['eye_edits_012043:Cornea_mat']} />
      <mesh geometry={nodes.VH_M_bulbar_conjunctiva_L.geometry} material={materials['eye_edits_012043:Bone_Mat']} />
      <mesh geometry={nodes.VH_M_iris_L.geometry} material={materials.pasted__iris_mat} />
      <mesh geometry={nodes.VH_M_trabecular_meshwork_L.geometry} material={materials['eye_edits_012042:meniscus_mat']} />
      <mesh geometry={nodes.VH_M_ciliary_body_L.geometry} material={materials['eye_edits_012042:lung_mat']}>
        <mesh geometry={nodes.VH_M_ciliary_muscle_L.geometry} material={materials['eye_edits_012042:lung_mat']} />
      </mesh>
      <mesh geometry={nodes.VH_M_aqueous_humor_L.geometry} material={materials.pasted__humours_mat} />
      <mesh geometry={nodes.VH_M_schlemms_canal_L.geometry} material={materials['eye_edits_012042:Skin_Mat']} />
      <mesh geometry={nodes.VH_M_lens_L.geometry} material={materials['eye_edits_012042:lens1']} />
      <mesh geometry={nodes.VH_M_corneo_scleral_junction_L.geometry} material={materials['eye_edits_012042:limbus1']} />
      <mesh geometry={nodes.VH_M_ora_serrata_of_retina_L.geometry} material={materials['eye_edits_012042:Ora_serrata_Mat']} />
      <mesh geometry={nodes.VH_M_suspensory_ligament_of_lens_L.geometry} material={materials['eye_edits_012042:iris_mat']} />
      <mesh geometry={nodes.VH_M_ciliary_processes_L.geometry} material={materials['eye_edits_012042:brain_mat1']} />
      <mesh geometry={nodes.VH_M_pupil_L.geometry} material={materials.pasted__pupil_mat} />
      <mesh geometry={nodes.VH_M_optic_choroid_L.geometry} material={materials.pasted__choroid_mat} />
      <mesh geometry={nodes.VH_M_sclera_L.geometry} material={materials['eye_edits_012046:Eyeball_Mat']} />
      <mesh geometry={nodes.VH_M_palpebral_conjunctiva_of_upper_eyelid_L.geometry} material={materials.pasted__pasted__pasted__pasted__conjunctiva_Mat1} />
      <mesh geometry={nodes.VH_M_palpebral_conjunctiva_of_lower_eyelid_L.geometry} material={materials.pasted__pasted__pasted__pasted__conjunctiva_Mat1} />
      <mesh geometry={nodes.VH_M_medial_rectus_extraocular_muscle_L.geometry} material={materials['eye_edits_012022:muscle_mat']} />
      <mesh geometry={nodes.VH_M_inferior_rectus_extraocular_muscle_L.geometry} material={materials['eye_edits_012022:muscle_mat']} />
      <mesh geometry={nodes.VH_M_superior_rectus_extraocular_muscle_L.geometry} material={materials['eye_edits_012022:muscle_mat']} />
      <mesh geometry={nodes.VH_M_inferior_oblique_extraocular_muscle_L.geometry} material={materials['eye_edits_012022:muscle_mat']} />
      <mesh geometry={nodes.VH_M_lateral_rectus_extraocular_muscle_L.geometry} material={materials['eye_edits_012022:muscle_mat']} />
      <mesh geometry={nodes.VH_M_superior_oblique_extraocular_muscle_L.geometry} material={materials['eye_edits_012022:muscle_mat']} />
      <mesh geometry={nodes.VH_M_superior_rectus_extraocular_muscle_R.geometry} material={materials.pasted__muscle_mat} />
      <mesh geometry={nodes.VH_M_medial_rectus_extraocular_muscle_R.geometry} material={materials['eye_edits_012022:muscle_mat']} />
      <mesh geometry={nodes.VH_M_inferior_rectus_extraocular_muscle_R.geometry} material={materials['eye_edits_012022:muscle_mat']} />
      <mesh geometry={nodes.VH_M_inferior_oblique_extraocular_muscle_R.geometry} material={materials['eye_edits_012022:muscle_mat']} />
      <mesh geometry={nodes.VH_M_lateral_rectus_extraocular_muscle_R.geometry} material={materials['eye_edits_012022:muscle_mat']} />
      <mesh geometry={nodes.VH_M_superior_oblique_extraocular_muscle_R.geometry} material={materials['eye_edits_012022:muscle_mat']} />
      <mesh geometry={nodes.VH_M_rectus_femoris_L.geometry} material={materials.muscle_Mat}>
        <mesh geometry={nodes.VH_M_tendon_of_quadriceps_femoris_L.geometry} material={materials.mucosa_mat} />
      </mesh>
      <mesh geometry={nodes.VH_M_rectus_femoris_R.geometry} material={materials.muscle_Mat}>
        <mesh geometry={nodes.VH_M_tendon_of_quadriceps_femoris_R.geometry} material={materials.mucosa_mat} />
      </mesh>
      <mesh geometry={nodes.VH_M_thyroepiglottideus.geometry} material={materials.muscle_Mat} />
      <mesh geometry={nodes.VH_M_vocalis.geometry} material={materials.muscle_Mat} />
      <mesh geometry={nodes.VH_M_arytenoid.geometry} material={materials.muscle_Mat} />
      <mesh geometry={nodes.VH_M_posterior_cricoarytenoid_L.geometry} material={materials.muscle_Mat} />
      <mesh geometry={nodes.VH_M_posterior_cricoarytenoid_R.geometry} material={materials.muscle_Mat} />
      <mesh geometry={nodes.VH_M_lateral_cricoarytenoid_R.geometry} material={materials.muscle_Mat} />
      <mesh geometry={nodes.VH_M_lateral_cricoarytenoid_L.geometry} material={materials.muscle_Mat} />
      <mesh geometry={nodes.VH_M_cricothyroid_R.geometry} material={materials.muscle_Mat} />
      <mesh geometry={nodes.VH_M_cricothyroid_L.geometry} material={materials.muscle_Mat} />
      <mesh geometry={nodes.VH_M_thyroarytenoid_L.geometry} material={materials.muscle_Mat} />
      <mesh geometry={nodes.VH_M_thyroarytenoid_R.geometry} material={materials.muscle_Mat} />
      <mesh geometry={nodes.VH_M_seminal_vesicle.geometry} material={materials.genitalDuct_mat} />
      <mesh geometry={nodes.VH_M_ejaculatory_duct.geometry} material={materials.genitalDuct_mat} />
      <mesh geometry={nodes.VH_M_vas_deferens_L.geometry} material={materials.genitalDuct_mat} />
      <mesh geometry={nodes.VH_M_vas_deferens_R.geometry} material={materials.genitalDuct_mat} />
      <mesh geometry={nodes.VH_M_prostatic_utricle.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_seminal_colliculus.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_apex_of_prostate.geometry} material={materials.Gland_Mat} />
      <mesh geometry={nodes.VH_M_base_of_prostate.geometry} material={materials.Gland_Mat} />
      <mesh geometry={nodes.VH_M_prostate_duct_R.geometry} material={materials.Gland_Mat} />
      <mesh geometry={nodes.VH_M_prostate_duct_L.geometry} material={materials.Gland_Mat} />
      <mesh geometry={nodes.VH_M_peripheral_zone_of_prostate_R.geometry} material={materials.Gland_Mat} />
      <mesh geometry={nodes.VH_M_peripheral_zone_of_prostate_L.geometry} material={materials.Gland_Mat} />
      <mesh geometry={nodes.VH_M_transition_zone__of_prostate_L.geometry} material={materials.Gland_Mat} />
      <mesh geometry={nodes.VH_M_transition_zone_of_prostate_R.geometry} material={materials.Gland_Mat} />
      <mesh geometry={nodes.VH_M_central_zone_of_prostate_R.geometry} material={materials.Gland_Mat} />
      <mesh geometry={nodes.VH_M_central_zone_of_prostate_L.geometry} material={materials.Gland_Mat} />
      <mesh geometry={nodes.VH_M_anterior_fibromuscular_stroma_L.geometry} material={materials.Gland_Mat} />
      <mesh geometry={nodes.VH_M_anterior_fibromuscular_stroma_R.geometry} material={materials.Gland_Mat} />
      <mesh geometry={nodes.VH_M_bare_area_of_liver.geometry} material={materials.Liver_Mat} />
      <mesh geometry={nodes.VH_M_liver_capsule.geometry} material={materials.Liver_Mat} />
      <mesh geometry={nodes.VH_M_diaphragmatic_surface.geometry} material={materials.Liver_Mat} />
      <mesh geometry={nodes.VH_M_suprarenal_impression_of_liver.geometry} material={materials.Liver_Mat} />
      <mesh geometry={nodes.VH_M_renal_impression_of_liver.geometry} material={materials.Liver_Mat} />
      <mesh geometry={nodes.VH_M_gastric_impression_of_liver.geometry} material={materials.Liver_Mat} />
      <mesh geometry={nodes.VH_M_colic_impression_of_liver.geometry} material={materials.Liver_Mat} />
      <mesh geometry={nodes.VH_M_esophageal_impression_of_liver.geometry} material={materials.Liver_Mat} />
      <mesh geometry={nodes.VH_M_duodenal_impression_of_liver.geometry} material={materials.Liver_Mat} />
      <mesh geometry={nodes.VH_M_porta_hepatis.geometry} material={materials.Liver_Mat} />
      <mesh geometry={nodes.VH_M_caudate_lobe_of_liver.geometry} material={materials.Liver_Mat} />
      <mesh geometry={nodes.VH_M_right_posteroinferior_segment.geometry} material={materials.Liver_Mat} />
      <mesh geometry={nodes.VH_M_right_posterosuperior_segment.geometry} material={materials.Liver_Mat} />
      <mesh geometry={nodes.VH_M_right_anterosuperior_segment.geometry} material={materials.Liver_Mat} />
      <mesh geometry={nodes.VH_M_right_anteroinferior_segment.geometry} material={materials.Liver_Mat} />
      <mesh geometry={nodes.VH_M_left_anterolateral_segment.geometry} material={materials.Liver_Mat} />
      <mesh geometry={nodes.VH_M_left_posterolateral_segment.geometry} material={materials.Liver_Mat} />
      <mesh geometry={nodes.VH_M_left_superiomedial_segment.geometry} material={materials.Liver_Mat} />
      <mesh geometry={nodes.VH_M_left_inferomedial_segment.geometry} material={materials.Liver_Mat}>
        <mesh geometry={nodes.VH_M_quadrate_lobe_of_liver.geometry} material={materials.Liver_Mat} />
      </mesh>
      <mesh geometry={nodes.VH_M_hepataduodenal_ligament.geometry} material={materials.Ligament_Mat} />
      <mesh geometry={nodes.VH_M_ligamentum_venosum.geometry} material={materials.Ligament_Mat} />
      <mesh geometry={nodes.VH_M_round_ligament_of_liver.geometry} material={materials.Ligament_Mat} />
      <mesh geometry={nodes.VH_M_triangular_ligament_of_liver.geometry} material={materials.Ligament_Mat} />
      <mesh geometry={nodes.VH_M_falciform_ligament.geometry} material={materials.Ligament_Mat} />
      <mesh geometry={nodes.VH_M_coronary_ligament_of_liver.geometry} material={materials.Ligament_Mat} />
      <mesh geometry={nodes.VH_M_body_of_pancreas.geometry} material={materials.Gland_Mat} />
      <mesh geometry={nodes.VH_M_tail_of_pancreas.geometry} material={materials.Gland_Mat} />
      <mesh geometry={nodes.VH_M_head_of_pancreas.geometry} material={materials.Gland_Mat} />
      <mesh geometry={nodes.VH_M_neck_of_pancreas.geometry} material={materials.Gland_Mat} />
      <mesh geometry={nodes.VH_M_uncinate_process_of_the_pancreas.geometry} material={materials.Gland_Mat} />
      <mesh geometry={nodes.VH_M_dorsal_pancreatic_duct.geometry} material={materials.bile_mat} />
      <mesh geometry={nodes.VH_M_common_bile_duct.geometry} material={materials.bile_mat} />
      <mesh geometry={nodes.VH_M_ventral_pancreatic_duct.geometry} material={materials.bile_mat} />
      <mesh geometry={nodes.VH_M_hepatopancreatic_ampulla.geometry} material={materials.bile_mat} />
      <mesh geometry={nodes.VH_M_right_hepatic_duct.geometry} material={materials.bile_mat} />
      <mesh geometry={nodes.VH_M_left_hepatic_duct.geometry} material={materials.bile_mat} />
      <mesh geometry={nodes.VH_M_common_hepatic_duct.geometry} material={materials.bile_mat} />
      <mesh geometry={nodes.VH_M_cystic_duct.geometry} material={materials.bile_mat} />
      <mesh geometry={nodes.VH_M_ileum.geometry} material={materials.sm_intestine}>
        <mesh geometry={nodes.VH_M_ileum_terminal.geometry} material={materials.sm_intestine} />
      </mesh>
      <mesh geometry={nodes.VH_M_jejunum.geometry} material={materials.sm_intestine} />
      <mesh geometry={nodes.VH_M_duodenum_ascending.geometry} material={materials.sm_intestine} />
      <mesh geometry={nodes.VH_M_duodenum_descending.geometry} material={materials.sm_intestine} />
      <mesh geometry={nodes.VH_M_duodenum_horizonal.geometry} material={materials.sm_intestine} />
      <mesh geometry={nodes.VH_M_duodenum_superior.geometry} material={materials.sm_intestine}>
        <mesh geometry={nodes.VH_M_duodenal_ampulla.geometry} material={materials.sm_intestine} />
      </mesh>
      <mesh geometry={nodes.VH_M_sphincter_of_hepatopancreatic_ampulla.geometry} material={materials.sm_intestine} />
      <mesh geometry={nodes.VH_M_papilla_of_santorini.geometry} material={materials.sm_intestine} />
      <mesh geometry={nodes.VH_M_ascending_colon.geometry} material={materials.colon_mat} />
      <mesh geometry={nodes.VH_M_descending_colon.geometry} material={materials.colon_mat} />
      <mesh geometry={nodes.VH_M_hepatic_flexure_of_colon.geometry} material={materials.colon_mat} />
      <mesh geometry={nodes.VH_M_rectum.geometry} material={materials.colon_mat} />
      <mesh geometry={nodes.VH_M_sigmoid_colon.geometry} material={materials.colon_mat} />
      <mesh geometry={nodes.VH_M_splenic_flexure_of_colon.geometry} material={materials.colon_mat} />
      <mesh geometry={nodes.VH_M_transverse_colon.geometry} material={materials.colon_mat} />
      <mesh geometry={nodes.VH_M_ileocecal_valve.geometry} material={materials.colon_mat} />
      <mesh geometry={nodes.VH_M_caecum.geometry} material={materials.colon_mat} />
      <mesh geometry={nodes.VH_M_vermiform_appendix.geometry} material={materials.colon_mat} />
      <mesh geometry={nodes.VH_M_gallbladder.geometry} material={materials.Gall_Mat} />
      <mesh geometry={nodes.VH_M_palatine_tonsil_L.geometry} material={materials['eye_edits_012022:lung_mat']} />
      <mesh geometry={nodes.VH_M_palatine_tonsil_R.geometry} material={materials['eye_edits_012022:lung_mat']} />
      <mesh geometry={nodes.VH_M_renal_pelvis_R.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_ureter_R.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_major_calyx_R_a.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_major_calyx_R_b.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_minor_calyx_R_a.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_minor_calyx_R_b.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_minor_calyx_R_c.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_minor_calyx_R_d.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_minor_calyx_R_e.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_minor_calyx_R_f.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_minor_calyx_R_g.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_minor_calyx_R_h.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_minor_calyx_R_i.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_renal_pelvis_L.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_ureter_L.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_major_calyx_L_a.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_major_calyx_L_b.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_major_calyx_L_c.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_minor_calyx_L_a.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_minor_calyx_L_b.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_minor_calyx_L_c.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_minor_calyx_L_d.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_minor_calyx_L_e.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_minor_calyx_L_f.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_minor_calyx_L_g.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_minor_calyx_L_h.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_minor_calyx_L_i.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_kidney_capsule_L.geometry} material={materials.kidneycapsule_mat} />
      <mesh geometry={nodes.VH_M_hilum_of_kidney_L.geometry} material={materials.kidneycapsule_mat} />
      <mesh geometry={nodes.VH_M_renal_column_L.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh geometry={nodes.VH_M_outer_cortex_of_kidney_L.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh geometry={nodes.VH_M_renal_papilla_L_a.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh geometry={nodes.VH_M_renal_papilla_L_b.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh geometry={nodes.VH_M_renal_papilla_L_c.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh geometry={nodes.VH_M_renal_papilla_L_d.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh geometry={nodes.VH_M_renal_papilla_L_e.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh geometry={nodes.VH_M_renal_papilla_L_f.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh geometry={nodes.VH_M_renal_papilla_L_g.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh geometry={nodes.VH_M_renal_papilla_L_h.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh geometry={nodes.VH_M_renal_papilla_L_i.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh geometry={nodes.VH_M_renal_pyramid_L_a.geometry} material={materials.kidney_pyramids_mat} />
      <mesh geometry={nodes.VH_M_renal_pyramid_L_b.geometry} material={materials.kidney_pyramids_mat} />
      <mesh geometry={nodes.VH_M_renal_pyramid_L_c.geometry} material={materials.kidney_pyramids_mat} />
      <mesh geometry={nodes.VH_M_renal_pyramid_L_d.geometry} material={materials.kidney_pyramids_mat} />
      <mesh geometry={nodes.VH_M_renal_pyramid_L_e.geometry} material={materials.kidney_pyramids_mat} />
      <mesh geometry={nodes.VH_M_renal_pyramid_L_f.geometry} material={materials.kidney_pyramids_mat} />
      <mesh geometry={nodes.VH_M_renal_pyramid_L_g.geometry} material={materials.kidney_pyramids_mat} />
      <mesh geometry={nodes.VH_M_renal_pyramid_L_h.geometry} material={materials.kidney_pyramids_mat} />
      <mesh geometry={nodes.VH_M_renal_pyramid_L_i.geometry} material={materials.kidney_pyramids_mat} />
      <mesh geometry={nodes.VH_M_kidney_capsule_R.geometry} material={materials.kidneycapsule_mat} />
      <mesh geometry={nodes.VH_M_hilum_of_kidney_R.geometry} material={materials.kidneycapsule_mat} />
      <mesh geometry={nodes.VH_M_renal_papilla_R_j.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh geometry={nodes.VH_M_renal_papilla_R_i.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh geometry={nodes.VH_M_renal_papilla_R_h.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh geometry={nodes.VH_M_renal_papilla_R_g.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh geometry={nodes.VH_M_renal_papilla_R_f.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh geometry={nodes.VH_M_renal_papilla_R_e.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh geometry={nodes.VH_M_renal_papilla_R_d.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh geometry={nodes.VH_M_renal_papilla_R_c.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh geometry={nodes.VH_M_renal_papilla_R_b.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh geometry={nodes.VH_M_renal_papilla_R_a.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh geometry={nodes.VH_M_renal_pyramid_a.geometry} material={materials.kidney_pyramids_mat} />
      <mesh geometry={nodes.VH_M_renal_pyramid_b.geometry} material={materials.kidney_pyramids_mat} />
      <mesh geometry={nodes.VH_M_renal_pyramid_c.geometry} material={materials.kidney_pyramids_mat} />
      <mesh geometry={nodes.VH_M_renal_pyramid_d.geometry} material={materials.kidney_pyramids_mat} />
      <mesh geometry={nodes.VH_M_renal_pyramid_e.geometry} material={materials.kidney_pyramids_mat} />
      <mesh geometry={nodes.VH_M_renal_pyramid_f.geometry} material={materials.kidney_pyramids_mat} />
      <mesh geometry={nodes.VH_M_renal_pyramid_g.geometry} material={materials.kidney_pyramids_mat} />
      <mesh geometry={nodes.VH_M_renal_pyramid_h.geometry} material={materials.kidney_pyramids_mat} />
      <mesh geometry={nodes.VH_M_renal_pyramid_i.geometry} material={materials.kidney_pyramids_mat} />
      <mesh geometry={nodes.VH_M_renal_pyramid_j.geometry} material={materials.kidney_pyramids_mat} />
      <mesh geometry={nodes.VH_M_renal_column_R.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh geometry={nodes.VH_M_outer_cortex_of_kidney_R.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh geometry={nodes.VH_M_urinary_bladder_neck_smooth_muscle.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_fundus_of_urinary_bladder_dome.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_fundus_of_urinary_bladder_base1.geometry} material={materials.ureter_mat}>
        <mesh geometry={nodes.VH_M_trigone_of_urinary_bladder.geometry} material={materials.ureter_mat} />
      </mesh>
      <mesh geometry={nodes.VH_M_ureteral_orifice_R.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_ureteral_orifice_L.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_other_urethra.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_prostatic_urethra.geometry} material={materials.ureter_mat} />
      <mesh geometry={nodes.VH_M_mitral_valve.geometry} material={materials.heart_mat} />
      <mesh geometry={nodes.VH_M_tricuspid_valve.geometry} material={materials.heart_mat} />
      <mesh geometry={nodes.VH_M_aortic_valve.geometry} material={materials.heart_mat} />
      <mesh geometry={nodes.VH_M_pulmonary_valve.geometry} material={materials.heart_mat} />
      <mesh geometry={nodes.VH_M_papillary_muscle_of_heart_anterior.geometry} material={materials.heart_mat} />
      <mesh geometry={nodes.VH_M_papillary_muscle_of_heart_anterolateral.geometry} material={materials.heart_mat} />
      <mesh geometry={nodes.VH_M_papillary_muscle_of_heart_medial.geometry} material={materials.heart_mat} />
      <mesh geometry={nodes.VH_M_papillary_muscle_of_heart_posterior.geometry} material={materials.heart_mat} />
      <mesh geometry={nodes.VH_M_papillary_muscle_of_heart_posteromedial.geometry} material={materials.heart_mat} />
      <mesh geometry={nodes.VH_M_left_cardiac_atrium.geometry} material={materials.heart_mat} />
      <mesh geometry={nodes.VH_M_right_cardiac_atrium.geometry} material={materials.heart_mat} />
      <mesh geometry={nodes.VH_M_heart_right_ventricle.geometry} material={materials.heart_mat} />
      <mesh geometry={nodes.VH_M_interventricular_septum.geometry} material={materials.heart_mat} />
      <mesh geometry={nodes.VH_M_heart_left_ventricle.geometry} material={materials.heart_mat} />
      <mesh geometry={nodes.VH_M_ophthalmic_vein_L.geometry} material={materials['eye_edits_012024:pasted__vein_mat']} />
      <mesh geometry={nodes.VH_M_superior_ophthalmic_vein_L.geometry} material={materials['eye_edits_012024:pasted__vein_mat']} />
      <mesh geometry={nodes.VH_M_inferior_ophthalmic_vein_L.geometry} material={materials['eye_edits_012024:pasted__vein_mat']} />
      <mesh geometry={nodes.VH_M_central_retinal_vein_L.geometry} material={materials['eye_edits_012024:pasted__vein_mat']} />
      <mesh geometry={nodes.VH_M_ophthalmic_vein_R.geometry} material={materials['eye_edits_012022:pasted__vein_mat']} />
      <mesh geometry={nodes.VH_M_superior_ophthalmic_vein_R.geometry} material={materials['eye_edits_012022:pasted__vein_mat']} />
      <mesh geometry={nodes.VH_M_inferior_ophthalmic_vein_R.geometry} material={materials['eye_edits_012022:pasted__vein_mat']} />
      <mesh geometry={nodes.VH_M_central_retinal_vein_R.geometry} material={materials['eye_edits_012022:pasted__vein_mat']} />
      <mesh geometry={nodes.VH_M_central_retinal_artery_L.geometry} material={materials['eye_edits_012024:pasted__artery_mat']} />
      <mesh geometry={nodes.VH_M_opthalmic_artery_L.geometry} material={materials['eye_edits_012024:pasted__artery_mat']} />
      <mesh geometry={nodes.VH_M_long_posterior_ciliary_artery_L.geometry} material={materials.pasted__pasted__dura_mater_mat} />
      <mesh geometry={nodes.VH_M_central_retinal_artery_R.geometry} material={materials['eye_edits_012022:pasted__artery_mat']} />
      <mesh geometry={nodes.VH_M_opthalmic_artery_R.geometry} material={materials['eye_edits_012022:pasted__artery_mat']} />
      <mesh geometry={nodes.VH_M_long_posterior_ciliary_artery_R.geometry} material={materials.pasted__dura_mater_mat} />
      <mesh geometry={nodes.VH_M_inferior_mesenteric_vein.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_median_sacral_vein.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_sigmoid_vein.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_superior_mesenteric_vein.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_superior_rectal_vein.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_inferior_pancreaticoduodenal_vein.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_common_iliac_vein_L.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_common_iliac_vein_R.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_external_iliac_vein_L.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_external_iliac_vein_R.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_inferior_rectal_vein_L.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_inferior_rectal_vein_R.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_internal_pudendal_vein_L.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_internal_pudendal_vein_R.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_internal_iliac_vein_L.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_internal_iliac_vein_R.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_left_colic_vein.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_ileocolic_vein.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_right_colic_vein.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_middle_colic_vein.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_middle_rectal_vein_L.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_middle_rectal_vein_R.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_inferior_mesenteric_artery.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_superior_mesenteric_artery.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_marginal_artery_of_Drummond.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_right_colic_artery.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_middle_colic_artery.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_left_colic_artery.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_ileocolic_artery.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_sigmoid_artery_a.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_sigmoid_artery_b.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_sigmoid_artery_c.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_renal_vein_L.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_renal_vein_R.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_left_renal_artery.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_right_renal_artery.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_aortic_arch.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_ascending_aorta.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_brachiocephalic_artery_b.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_brachiocephalic_artery_a.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_left_common_carotid_artery_a.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_left_common_carotid_artery_b.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_left_subclavian_artery_a.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_left_subclavian_artery_b.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_descending_aorta_a.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_descending_aorta_b.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_left_anterior_descending_artery.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_right_marginal_artery.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_right_posterior_descending_artery.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_diagonal_branch_of_anterior_descending_branch_of_left_coronary_artery.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_left_coronary_artery.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_right_coronary_artery.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_diagonal_branch_of_left_anterior_descending_artery.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_left_marginal_branch.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_pulmonary_artery_L.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_pulmonary_artery_R.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_pulmonary_trunk.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_great_cardiac_vein.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_middle_cardiac_vein.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_oblique_vein_of_left_atrium.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_anterior_cardiac_vein.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_coronary_sinus.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_posterior_vein_of_left_ventricle.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_small_cardiac_vein.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_pulmonary_vein_R_inf.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_pulmonary_vein_R_sup.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_pulmonary_vein_L_inf.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_pulmonary_vein_L_sup.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_brachiocephalic_vein_L.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_brachiocephalic_vein_R.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_superior_vena_cava.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_inferior_vena_cava_b.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_inferior_vena_cava_a.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_splenic_vein.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_splenic_artery.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_cystic_vein.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_cystic_artery.geometry} material={materials.phong4} />
      <mesh geometry={nodes.VH_M_celiac_trunk.geometry} material={materials.phong4} />
      <mesh geometry={nodes.VH_M_left_hepatic_artery.geometry} material={materials.phong4} />
      <mesh geometry={nodes.VH_M_proper_hepatic_artery.geometry} material={materials.phong4} />
      <mesh geometry={nodes.VH_M_posterior_segmental_right_hepatic_artery.geometry} material={materials.phong4} />
      <mesh geometry={nodes.VH_M_right_hepatic_artery.geometry} material={materials.phong4} />
      <mesh geometry={nodes.VH_M_anterior_segmental_right_hepatic_artery.geometry} material={materials.phong4} />
      <mesh geometry={nodes.VH_M_common_hepatic_artery.geometry} material={materials.phong4} />
      <mesh geometry={nodes.VH_M_middle_hepatic_artery_branch_of_left_hepatic_artery.geometry} material={materials.phong4} />
      <mesh geometry={nodes.VH_M_right_hepatic_vein.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_left_hepatic_vein.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_middle_hepatic_vein.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_left_branch_of_portal_vein.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_right_branch_of_portal_vein.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_portal_vein.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_hepatic_portal_vein.geometry} material={materials.vein_mat} />
      <mesh geometry={nodes.VH_M_hilum_L.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_M_hilum_upper_L.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_M_left_lingula_superior_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_M_left_posterior_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_M_left_anterior_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_M_left_apical_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_M_left_lingula_inferior_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_M_hilum_lower_L.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_M_left_anterior_basal_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_M_left_lateral_basal_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_M_left_medial_basal_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_M_left_posetrior_basal_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_M_left_superior_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_M_hilum_R.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_M_right_lateral_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_M_right_medial_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_M_hilum_middle_R.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_M_hilum_lower_R.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_M_right_anterior_basal_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_M_right_lateral_basal_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_M_right_medial_basal_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_M_right_posterior_basal_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_M_right_superior_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_M_right_apical_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_M_right_posterior_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_M_right_anterior_bronchopulmonary_segment.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_M_hilum_upper_R.geometry} material={materials.lung_mat} />
      <mesh geometry={nodes.VH_M_epiglottic_cartilage.geometry} material={materials.Cartilage_Mat} />
      <mesh geometry={nodes.VH_M_cricoid_cartilage.geometry} material={materials.Cartilage_Mat} />
      <mesh geometry={nodes.VH_M_thyroid_cartilage.geometry} material={materials.Cartilage_Mat} />
      <mesh geometry={nodes.VH_M_arytenoid_cartilage_R.geometry} material={materials.Cartilage_Mat} />
      <mesh geometry={nodes.VH_M_arytenoid_cartilage_L.geometry} material={materials.Cartilage_Mat} />
      <mesh geometry={nodes.VH_M_corniculate_cartilage_L.geometry} material={materials.Cartilage_Mat} />
      <mesh geometry={nodes.VH_M_corniculate_cartilage_R.geometry} material={materials.Cartilage_Mat} />
      <mesh geometry={nodes.VH_M_trachea.geometry} material={materials.mucosa_mat}>
        <mesh geometry={nodes.VH_M_tracheal_cartilage.geometry} material={materials.Cartilage_Mat} />
        <mesh geometry={nodes.VH_M_carina.geometry} material={materials.Cartilage_Mat} />
      </mesh>
      <mesh geometry={nodes.VH_M_left_main_bronchus.geometry} material={materials.mucosa_mat}>
        <mesh geometry={nodes.VH_M_cartilage_of_the_main_bronchus_L.geometry} material={materials.VH_M_leftFBXASC032mainFBXASC032bronchusFBXASC032bronchial_cartilage_ncl1_2} />
      </mesh>
      <mesh geometry={nodes.VH_M_right_main_bronchus.geometry} material={materials.mucosa_mat}>
        <mesh geometry={nodes.VH_M_cartilage_of_the_main_bronchus_R.geometry} material={materials.VH_M_rightFBXASC032mainFBXASC032bronchusFBXASC032bronchial_cartilage_ncl1_2} />
      </mesh>
      <mesh geometry={nodes.VH_M_cartilage_of_the_lobar_bronchus_L.geometry} material={materials.VH_M_leftFBXASC032lobarFBXASC032bronchusFBXASC032bronchial_cartilage_ncl1_2} />
      <mesh geometry={nodes.VH_M_cartilage_of_the_tertiary_bronchus_L.geometry} material={materials.VH_M_leftFBXASC032tertiaryFBXASC032bronchial_cartilage_ncl1_2} />
      <mesh geometry={nodes.VH_M_left_superior_lobar_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_M_left_inferior_lobar_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_M_left_superior_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_M_left_posterior_basal_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_M_left_medial_basal_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_M_left_apical_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_M_left_anterior_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_M_left_lingular_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_M_left_lingula_superior_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_M_left_lingula_inferior_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_M_left_lateral_basal_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_M_left_anterior_basal_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_M_cartilage_of_the_lobar_bronchus_R.geometry} material={materials.VH_M_rightFBXASC032lobarFBXASC032bronchial_cartilage2_ncl1_2} />
      <mesh geometry={nodes.VH_M_cartilage_of_the_tertiary_bronchus_R.geometry} material={materials.VH_M_rightFBXASC032tertiaryFBXASC032bronchial_cartilage1_ncl1_2} />
      <mesh geometry={nodes.VH_M_right_intermediate_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_M_right_middle_lobar_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_M_right_superior_lobar_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_M_right_anterior_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_M_right_lateral_basal_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_M_right_lateral_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_M_right_lower_lobar_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_M_right_medial_basal_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_M_right_medial_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_M_right_posterior_basal.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_M_right_posterior_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_M_right_superior_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_M_right_apical_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_M_right_anterior_basal_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_M_bronchus.geometry} material={materials.mucosa_mat} />
      <mesh geometry={nodes.VH_M_colic_surface_of_spleen.geometry} material={materials.spleen_mat} />
      <mesh geometry={nodes.VH_M_diaphragmatic_surface_of_spleen.geometry} material={materials.spleen_mat} />
      <mesh geometry={nodes.VH_M_gastric_surface_of_spleen.geometry} material={materials.spleen_mat} />
      <mesh geometry={nodes.VH_M_hilum_of_spleen.geometry} material={materials.spleen_mat} />
      <mesh geometry={nodes.VH_M_renal_surface_of_spleen.geometry} material={materials.spleen_mat} />
      <mesh geometry={nodes.Yao_afferent_lymphatic_vessel.geometry} material={materials.Lymph_mat} />
      <mesh geometry={nodes.Yao_capsule_of_lymph_node.geometry} material={materials.Lymph_mat} />
      <mesh geometry={nodes.Yao_follicles.geometry} material={materials.lymph_cortex_mat} />
      <mesh geometry={nodes.Yao_efferent_lymph_node.geometry} material={materials.Lymph_mat} />
      <mesh geometry={nodes.Yao_medulla_of_lymph_node.geometry} material={materials.lymph_medulla_mat} />
      <mesh geometry={nodes.Yao_paracortex.geometry} material={materials.lymph_paracortex_mat} />
      <mesh geometry={nodes.Yao_blood_vasculature.geometry} material={materials.artery_mat} />
      <mesh geometry={nodes.VH_M_thymus_lobe_L.geometry} material={materials.Gland_Mat} />
      <mesh geometry={nodes.VH_M_thymus_lobe_R.geometry} material={materials.Gland_Mat} />
      <mesh geometry={nodes.VH_M_hyoid.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_M_sacrum.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_M_coccyx.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_M_pubis_compact_bone_L.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_M_pubis_compact_bone_R.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_M_pubis_spongy_bone_L.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_M_pubis_spongy_bone_R.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_M_ilium_compact_bone_L.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_M_ilium_compact_bone_R.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_M_ilium_spongy_bone_R.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_M_ilium_spongy_bone_L.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_M_ischium_compact_bone_L.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_M_ischium_compact_bone_R.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_M_ischium_spongy_bone_L.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_M_ischium_spongy_bone_R.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_M_anterior_cruciate_ligament_of_knee_joint_R.geometry} material={materials.Cartilage_Mat} />
      <mesh geometry={nodes.VH_M_fibular_collateral_ligament_R.geometry} material={materials.Cartilage_Mat} />
      <mesh geometry={nodes.VH_M_right_tibial_collaterial_ligament.geometry} material={materials.Cartilage_Mat} />
      <mesh geometry={nodes.VH_M_posterior_cruciate_ligament_of_knee_joint_R.geometry} material={materials.Cartilage_Mat} />
      <mesh geometry={nodes.VH_M_anterolateral_ligament_of_knee_R.geometry} material={materials.Cartilage_Mat} />
      <mesh geometry={nodes.VH_M_patellar_ligament_R.geometry} material={materials.Cartilage_Mat} />
      <mesh geometry={nodes.VH_M_meniscus_R.geometry} material={materials.meniscus_mat} />
      <mesh geometry={nodes.VH_M_tibia_R.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_M_fibula_R.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_M_patella_R.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_M_femur_R.geometry} material={materials.Bone_Mat}>
        <mesh geometry={nodes.VH_M_articular_cartilage_of_knee_R.geometry} material={materials.Cartilage_Mat} />
        <mesh geometry={nodes.VH_M_intercondylar_fossa_R.geometry} material={materials.Bone_Mat}>
          <mesh geometry={nodes.VH_M_anterior_cruciate_enthesis_R.geometry} material={materials.Bone_Mat} />
          <mesh geometry={nodes.VH_M_posterior_cruciate_enthesis_R.geometry} material={materials.Bone_Mat} />
        </mesh>
        <mesh geometry={nodes.VH_M_lateral_condyle_of_femur_frontal_R.geometry} material={materials.Cartilage_Mat} />
        <mesh geometry={nodes.VH_M_lateral_condyle_of_femur_inf_R.geometry} material={materials.Cartilage_Mat} />
        <mesh geometry={nodes.VH_M_lateral_condyle_of_femur_sup_R.geometry} material={materials.Cartilage_Mat} />
        <mesh geometry={nodes.VH_M_lateral_epicondylar_enthesis_R.geometry} material={materials.Bone_Mat} />
        <mesh geometry={nodes.VH_M_lateral_perichondular_surface_R.geometry} material={materials.Bone_Mat} />
        <mesh geometry={nodes.VH_M_distal_most_point_of_medial_condyle_of_femur_R.geometry} material={materials.Cartilage_Mat} />
        <mesh geometry={nodes.VH_M_medial_condyle_of_right_femur_inf.geometry} material={materials.Cartilage_Mat} />
        <mesh geometry={nodes.VH_M_medial_condyle_of_right_femur_sup.geometry} material={materials.Cartilage_Mat} />
        <mesh geometry={nodes.VH_M_medial_epicondylar_enthesis_R.geometry} material={materials.Bone_Mat} />
        <mesh geometry={nodes.VH_M_medial_perichondular_surface_R.geometry} material={materials.Bone_Mat} />
        <mesh geometry={nodes.VH_M_patellar_surface_R.geometry} material={materials.Cartilage_Mat} />
      </mesh>
      <mesh geometry={nodes.VH_M_anterolateral_ligament_of_knee_L.geometry} material={materials.Cartilage_Mat} />
      <mesh geometry={nodes.VH_M_fibular_collateral_ligament_L.geometry} material={materials.Cartilage_Mat} />
      <mesh geometry={nodes.VH_M_posterior_cruciate_ligament_of_knee_joint_L.geometry} material={materials.Cartilage_Mat} />
      <mesh geometry={nodes.VH_M_left_tibial_collateral_ligament.geometry} material={materials.Cartilage_Mat} />
      <mesh geometry={nodes.VH_M_anterior_cruciate_ligament_of_knee_joint_L.geometry} material={materials.Cartilage_Mat} />
      <mesh geometry={nodes.VH_M_patellar_ligament_L.geometry} material={materials.Cartilage_Mat} />
      <mesh geometry={nodes.VH_M_meniscus_L.geometry} material={materials.meniscus_mat} />
      <mesh geometry={nodes.VH_M_fibula_L.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_M_femur_L.geometry} material={materials.Bone_Mat}>
        <mesh geometry={nodes.VH_M_articular_cartilage_of_knee_L.geometry} material={materials.Cartilage_Mat} />
        <mesh geometry={nodes.VH_M_intercondylar_fossa_L.geometry} material={materials.Bone_Mat}>
          <mesh geometry={nodes.VH_M_anterior_cruciate_enthesis_L.geometry} material={materials.Bone_Mat} />
          <mesh geometry={nodes.VH_M_posterior_cruciate_enthesis_L.geometry} material={materials.Bone_Mat} />
        </mesh>
        <mesh geometry={nodes.VH_M_lateral_condyle_of_femur_frontal_L.geometry} material={materials.Cartilage_Mat} />
        <mesh geometry={nodes.VH_M_lateral_condyle_of_femur_inf_L.geometry} material={materials.Cartilage_Mat} />
        <mesh geometry={nodes.VH_M_lateral_condyle_of_femur_sup_L.geometry} material={materials.Cartilage_Mat} />
        <mesh geometry={nodes.VH_M_lateral_epicondylar_enthesis_L.geometry} material={materials.Bone_Mat} />
        <mesh geometry={nodes.VH_M_lateral_perichondular_surface_L.geometry} material={materials.Bone_Mat} />
        <mesh geometry={nodes.VH_M_distal_most_point_of_medial_condyle_of_femur_L.geometry} material={materials.Cartilage_Mat} />
        <mesh geometry={nodes.VH_M_medial_condyle_of_left_femur_inf.geometry} material={materials.Cartilage_Mat} />
        <mesh geometry={nodes.VH_M_medial_condyle_of_left_femur_sup.geometry} material={materials.Cartilage_Mat} />
        <mesh geometry={nodes.VH_M_medial_epicondylar_enthesis_L.geometry} material={materials.Bone_Mat} />
        <mesh geometry={nodes.VH_M_medial_perichondular_surface_L.geometry} material={materials.Bone_Mat} />
        <mesh geometry={nodes.VH_M_patellar_surface_L.geometry} material={materials.Cartilage_Mat} />
      </mesh>
      <mesh geometry={nodes.VH_M_tibia_L.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_M_patella_L.geometry} material={materials.Bone_Mat} />
      <mesh geometry={nodes.VH_M_cervical_vertebra_1.geometry} material={materials.pasted__Bone_Mat} />
      <mesh geometry={nodes.VH_M_cervical_vertebra_2.geometry} material={materials.pasted__Bone_Mat} />
      <mesh geometry={nodes.VH_M_cervical_vertebra_3.geometry} material={materials.pasted__Bone_Mat} />
      <mesh geometry={nodes.VH_M_cervical_vertebra_4.geometry} material={materials.pasted__Bone_Mat} />
      <mesh geometry={nodes.VH_M_cervical_vertebra_5.geometry} material={materials.pasted__Bone_Mat} />
      <mesh geometry={nodes.VH_M_cervical_vertebra_6.geometry} material={materials.pasted__Bone_Mat} />
      <mesh geometry={nodes.VH_M_cervical_vertebra_7.geometry} material={materials.pasted__Bone_Mat} />
      <mesh geometry={nodes.VH_M_thoracic_vertebra_1.geometry} material={materials.pasted__Bone_Mat} />
      <mesh geometry={nodes.VH_M_thoracic_vertebra_2.geometry} material={materials.pasted__Bone_Mat} />
      <mesh geometry={nodes.VH_M_thoracic_vertebra_3.geometry} material={materials.pasted__Bone_Mat} />
      <mesh geometry={nodes.VH_M_thoracic_vertebra_4.geometry} material={materials.pasted__Bone_Mat} />
      <mesh geometry={nodes.VH_M_thoracic_vertebra_5.geometry} material={materials.pasted__Bone_Mat} />
      <mesh geometry={nodes.VH_M_thoracic_vertebra_6.geometry} material={materials.pasted__Bone_Mat} />
      <mesh geometry={nodes.VH_M_thoracic_vertebra_7.geometry} material={materials.pasted__Bone_Mat} />
      <mesh geometry={nodes.VH_M_thoracic_vertebra_8.geometry} material={materials.pasted__Bone_Mat} />
      <mesh geometry={nodes.VH_M_thoracic_vertebra_9.geometry} material={materials.pasted__Bone_Mat} />
      <mesh geometry={nodes.VH_M_thoracic_vertebra_10.geometry} material={materials.pasted__Bone_Mat} />
      <mesh geometry={nodes.VH_M_thoracic_vertebra_11.geometry} material={materials.pasted__Bone_Mat} />
      <mesh geometry={nodes.VH_M_thoracic_vertebra_12.geometry} material={materials.pasted__Bone_Mat} />
      <mesh geometry={nodes.VH_M_lumbar_vertebra_1.geometry} material={materials.pasted__Bone_Mat} />
      <mesh geometry={nodes.VH_M_lumbar_vertebra_2.geometry} material={materials.pasted__Bone_Mat} />
      <mesh geometry={nodes.VH_M_lumbar_vertebra_3.geometry} material={materials.pasted__Bone_Mat} />
      <mesh geometry={nodes.VH_M_lumbar_vertebra_4.geometry} material={materials.pasted__Bone_Mat} />
      <mesh geometry={nodes.VH_M_lumbar_vertebra_5.geometry} material={materials.pasted__Bone_Mat} />
    </group>
  )
}

useGLTF.preload('/anatomy-opt.glb', 'https://www.gstatic.com/draco/versioned/decoders/1.5.5/')
